# Extending Fluopy with custom fluorophores and transitions

This notebook shows how to supply your own fluorophore data and define additional
photophysical processes using Fluopy's public objects. It assumes familiarity
with setting up a FluorophoreSystem and TransitionSet in the introductory tutorial.

Each example builds its own system and can be run separately. The spectra and
rates are illustrative inputs for demonstrating the API, rather than a calibrated
model of a particular dye.

## Main objects

| Object | Purpose |
|---|---|
| Spectrum | Wavelength-dependent emission or absorption data |
| FluorophoreData | Spectra and photophysical constants of one fluorophore type |
| Fluorophore | A named fluorophore, its position, and its data |
| SingleState | A state occupied by one fluorophore |
| PairedState | The states of an ordered donor–acceptor pair |
| TransitionType | Initial and final states, abbreviation, photon emission, and mechanism |
| Transition | A transition type, rate, and the fluorophore identities it applies to |
| TransitionSet | The transitions and state space of a fluorophore system |

A paired TransitionType requires a mechanism. Use TransitionMechanism.FRET for
FRET, or supply another mechanism name for a process whose rate you define
separately. Single-state transition types use the default mechanism=None.

Fluorophore identities are their positions in FluorophoreSystem.fluorophores;
obtain them with FluorophoreSystem.get_identity(). Fluorophores with the same
name must share the same FluorophoreData object and single-state transitions and
rates. Use distinct names when defining different kinetic models.

## Define a custom fluorophore from arrays

Construct the spectra, collect them and the photophysical constants in a
FluorophoreData object, and pass that object to the fluorophore's constants
parameter. FluorophoreSystem.load_transitions() then derives the built-in
transitions supported by those inputs.

The s0 absorption spectrum supplies absolute molar extinction coefficients for
deriving excitation at the chosen wavelength. Emission intensities may be
relative. An emission spectrum is needed for spectral filtering and for using
the fluorophore as a FRET donor.

The table below shows the excitation, fluorescent emission, and internal
conversion transitions derived for this simple dye.

In [1]:
import numpy as np

import fluopy

wavelengths = np.array([600, 620, 640, 660, 680])

emission = fluopy.fluo_data.Spectrum.from_arrays(
    wavelengths=wavelengths,
    values=[0.0, 0.2, 1.0, 0.6, 0.1],
)
absorption_s0 = fluopy.fluo_data.Spectrum.from_arrays(
    wavelengths=wavelengths,
    values=[10000, 40000, 80000, 30000, 5000],
)

custom_data = fluopy.fluo_data.FluorophoreData(
    QUANTUM_YIELD=0.6,
    FLUORESCENCE_LIFETIME=3e-9,
    emission_spectrum=emission,
    absorption_spectra={"s0": absorption_s0},
)

custom_fluorophore = fluopy.fluorophores.Fluorophore(
    name="custom",
    position=[0, 0],
    constants=custom_data,
)

fluorophore_system = fluopy.fluorophores.FluorophoreSystem(
    fluorophores=[custom_fluorophore],
)

transitions = fluorophore_system.load_transitions(
    wavelength=640,
    energy_transfer=False,
)
transition_set = fluopy.transitions.TransitionSet(
    transitions=transitions,
    fluorophore_system=fluorophore_system,
)

transition_set.transition_df[["abbreviation", "initial_state", "final_state", "rate"]]

                     abbreviation  ...          rate
Fluorophore identity               ...
custom      0                 EXC  ...  1.971006e+06
            1                 FLU  ...  2.000000e+08
            2                  IC  ...  1.333333e+08

[3 rows x 4 columns]

## Load custom spectra from CSV files

Spectrum.from_csv() reads columns named Wavelengths and y by default. Supply
wavelength_column and value_column when your CSV uses different column names.

This example loads the bundled Atto643 spectra so it can run without external
files. Replace these paths with your experimental spectra. The other constants
remain illustrative; this example demonstrates loading data, rather than
reproducing the bundled Atto643 model.

In [2]:
from pathlib import Path

import fluopy

spectrum_dir = Path(fluopy.__file__).parent / "fluorophore_spectra" / "atto643_data"

custom_data = fluopy.fluo_data.FluorophoreData(
    QUANTUM_YIELD=0.6,
    FLUORESCENCE_LIFETIME=3e-9,
    emission_spectrum=fluopy.fluo_data.Spectrum.from_csv(spectrum_dir / "emission.csv"),
    absorption_spectra={
        "s0": fluopy.fluo_data.Spectrum.from_csv(spectrum_dir / "absorption_s0.csv"),
    },
)

custom_fluorophore = fluopy.fluorophores.Fluorophore(
    name="custom",
    position=[0, 0],
    constants=custom_data,
)
fluorophore_system = fluopy.fluorophores.FluorophoreSystem(
    fluorophores=[custom_fluorophore],
)
transitions = fluorophore_system.load_transitions(
    wavelength=640,
    energy_transfer=False,
)
transition_set = fluopy.transitions.TransitionSet(
    transitions=transitions,
    fluorophore_system=fluorophore_system,
)

transition_set.transition_df[["abbreviation", "initial_state", "final_state", "rate"]]

                     abbreviation  ...          rate
Fluorophore identity               ...
custom      0                 EXC  ...  3.577376e+06
            1                 FLU  ...  2.000000e+08
            2                  IC  ...  1.333333e+08

[3 rows x 4 columns]

## Use an individual absorption cross section

Some built-in light-driven processes use a single absorption cross section at
the excitation wavelength. For photoinduced back-isomerization from cis to S0,
provide BISO_CROSS_SECTION in cm² and record its wavelength in
CROSS_SECTION_WAVELENGTH. Fluopy derives the rate from the photon flux and this
cross section. Standard excitation from S0 still uses the s0 absorption spectrum.

This example changes those two fields in the bundled Cy5 data using
dataclasses.replace(), which creates a new FluorophoreData object. Its other
constants and spectra are preserved. The table shows excitation, formation of
cis, and photoinduced recovery from cis.

The cross section is an illustrative value at 640 nm. Use a value appropriate
to your excitation wavelength; Fluopy warns when it differs from
CROSS_SECTION_WAVELENGTH and does not interpolate the scalar cross section.

In [3]:
from dataclasses import replace

import fluopy

custom_data = replace(
    fluopy.fluo_data.cy5_dna,
    BISO_CROSS_SECTION=2e-18,
    CROSS_SECTION_WAVELENGTH=640,
)
custom_fluorophore = fluopy.fluorophores.Fluorophore(
    name="custom_cy5", position=[0, 0], constants=custom_data
)
fluorophore_system = fluopy.fluorophores.FluorophoreSystem([custom_fluorophore])
transitions = fluorophore_system.load_transitions(
    irradiance=2,
    wavelength=640,
    energy_transfer=False,
    dstorm=False,
)
transition_set = fluopy.transitions.TransitionSet(
    transitions=transitions,
    fluorophore_system=fluorophore_system,
)

transition_set.transition_df.loc[
    transition_set.transition_df["abbreviation"].isin(["EXC", "ISO", "PBISO"]),
    ["abbreviation", "initial_state", "final_state", "rate"],
]

                     abbreviation  ...          rate
Fluorophore identity               ...
custom_cy5  0                 EXC  ...  5.815700e+06
            4                 ISO  ...  4.000000e+06
            5               PBISO  ...  1.288734e+04

[3 rows x 4 columns]

## Add a custom single-fluorophore transition

Here an excited fluorophore can enter a custom DARK state and recover to S0.
Define a SingleState and TransitionTypes for entering and leaving it, then add
their Transition objects under the fluorophore's name.

Each SingleState needs a name and numerical value that do not conflict with
another state in the TransitionSet. The rates in this example are supplied
directly, so no spectra or photophysical constants are needed to construct the
dynamics. The recovery transition makes DARK reversible.

In [4]:
import fluopy

custom_data = fluopy.fluo_data.FluorophoreData()
custom_fluorophore = fluopy.fluorophores.Fluorophore(
    name="custom",
    position=[0, 0],
    constants=custom_data,
)
fluorophore_system = fluopy.fluorophores.FluorophoreSystem(
    fluorophores=[custom_fluorophore],
)
dark = fluopy.transitions.SingleState(name="DARK", value=10)

dark_formation = fluopy.transitions.TransitionType(
    abbreviation="DARK_FORM",
    initial_state=fluopy.transitions.SingleState.S1,
    final_state=dark,
    photon=False,
)
recovery = fluopy.transitions.TransitionType(
    abbreviation="REC",
    initial_state=dark,
    final_state=fluopy.transitions.SingleState.S0,
    photon=False,
)

transitions = {
    "custom": [
        fluopy.transitions.Transition(
            transition_type=fluopy.transitions.TransitionType.EXCITATION,
            rate=1e6,
            fluorophore_ids=[0],
        ),
        fluopy.transitions.Transition(
            transition_type=fluopy.transitions.TransitionType.FLUORESCENT_EMISSION,
            rate=1e8,
            fluorophore_ids=[0],
        ),
        fluopy.transitions.Transition(
            transition_type=dark_formation,
            rate=1e4,
            fluorophore_ids=[0],
        ),
        fluopy.transitions.Transition(
            transition_type=recovery,
            rate=1e3,
            fluorophore_ids=[0],
        ),
    ]
}

transition_set = fluopy.transitions.TransitionSet(
    transitions=transitions,
    fluorophore_system=fluorophore_system,
)

transition_set.transition_df[["abbreviation", "initial_state", "final_state", "rate"]]

                     abbreviation  ...         rate
Fluorophore identity               ...
custom      0                 EXC  ...    1000000.0
            1                 FLU  ...  100000000.0
            2           DARK_FORM  ...      10000.0
            3                 REC  ...       1000.0

[4 rows x 4 columns]

## Add a custom paired PET transition

PairedState describes the states of an ordered donor–acceptor pair. A paired
transition is available when both fluorophores match its initial states. Its
final states specify what happens to each fluorophore.

Here photoinduced electron transfer (PET) converts an excited donor and a
ground-state acceptor into an oxidized donor and a reduced acceptor. A paired
charge-recombination transition returns both fluorophores to S0. Custom
SingleStates represent the two charge states.

Use TransitionMechanism.PET to label the forward process. Supply pet_rate from
your own rate calculation or measurements; the value below is illustrative.
Fluopy uses this supplied rate alongside the other available transitions. The
mechanism label does not calculate a rate, and the spectral FRET helper does
not provide a PET rate. Supply the recombination rate independently as well.

Supply fluorophore_ids as a list of (donor_id, acceptor_id) tuples. The dictionary
key must contain the donor name, acceptor name, and distance in the format shown
below. Read the distance from the system so the key agrees with its geometry.
The component SingleStates are automatically included in each fluorophore's
state space.

In [5]:
import fluopy

donor = fluopy.fluorophores.Fluorophore(
    name="donor",
    position=[0, 0],
    constants=fluopy.fluo_data.FluorophoreData(),
)
acceptor = fluopy.fluorophores.Fluorophore(
    name="acceptor",
    position=[5, 0],
    constants=fluopy.fluo_data.FluorophoreData(),
)
fluorophore_system = fluopy.fluorophores.FluorophoreSystem([donor, acceptor])

oxidized = fluopy.transitions.SingleState(name="OXIDIZED", value=10)
reduced = fluopy.transitions.SingleState(name="REDUCED", value=11)
charge_separated = fluopy.transitions.PairedState(
    name="OXIDIZED_REDUCED",
    donor=oxidized,
    acceptor=reduced,
)
pet = fluopy.transitions.TransitionType(
    abbreviation="PET",
    initial_state=fluopy.transitions.PairedState.S1_S0,
    final_state=charge_separated,
    photon=False,
    mechanism=fluopy.transitions.TransitionMechanism.PET,
)
recombination = fluopy.transitions.TransitionType(
    abbreviation="CR",
    initial_state=charge_separated,
    final_state=fluopy.transitions.PairedState.S0_S0,
    photon=False,
    mechanism="CHARGE_RECOMBINATION",
)

pet_rate = 1e7
recombination_rate = 1e5
donor_id = fluorophore_system.get_identity(donor)
acceptor_id = fluorophore_system.get_identity(acceptor)
pair = (donor_id, acceptor_id)
distance = fluorophore_system.distances[pair]
transition_key = f"D: {donor.name}, A: {acceptor.name}, dist: {distance}"

transitions = {
    donor.name: [
        fluopy.transitions.Transition(
            fluopy.transitions.TransitionType.EXCITATION,
            rate=1e6,
            fluorophore_ids=[donor_id],
        ),
        fluopy.transitions.Transition(
            fluopy.transitions.TransitionType.FLUORESCENT_EMISSION,
            rate=1e8,
            fluorophore_ids=[donor_id],
        ),
    ],
    acceptor.name: [
        fluopy.transitions.Transition(
            fluopy.transitions.TransitionType.EXCITATION,
            rate=1e6,
            fluorophore_ids=[acceptor_id],
        ),
        fluopy.transitions.Transition(
            fluopy.transitions.TransitionType.FLUORESCENT_EMISSION,
            rate=1e8,
            fluorophore_ids=[acceptor_id],
        ),
    ],
    transition_key: [
        fluopy.transitions.Transition(pet, rate=pet_rate, fluorophore_ids=[pair]),
        fluopy.transitions.Transition(
            recombination, rate=recombination_rate, fluorophore_ids=[pair]
        ),
    ],
}

transition_set = fluopy.transitions.TransitionSet(
    transitions=transitions,
    fluorophore_system=fluorophore_system,
)

transition_set.transition_df[["abbreviation", "initial_state", "final_state", "rate"]]

                                          abbreviation  ...         rate
Fluorophore                      identity               ...
donor                            0                 EXC  ...    1000000.0
                                 1                 FLU  ...  100000000.0
acceptor                         2                 EXC  ...    1000000.0
                                 3                 FLU  ...  100000000.0
D: donor, A: acceptor, dist: 5.0 4                 PET  ...   10000000.0
                                 5                  CR  ...     100000.0

[6 rows x 4 columns]

## Derive standard FRET automatically from custom spectra

With energy_transfer=True, FluorophoreSystem.load_transitions() derives FRET
rates from donor emission and acceptor absorption spectra. The calculation uses
their spectral overlap, the donor quantum yield and fluorescence lifetime, the
distance, the dipole orientation factor, and the refractive index.

The fluorophore positions set the distance in nm. Supply dipole_orientation_factor
and refractive_index through energy_transfer_parameters. Both ordered directions
are considered, so these spectra produce forward and reverse FRET transitions.

In [6]:
import fluopy

wavelengths = [500, 525, 550, 575, 600]
donor_emission = fluopy.fluo_data.Spectrum(
    wavelengths=wavelengths,
    values=[0.0, 0.4, 1.0, 0.6, 0.1],
)
donor_absorption = fluopy.fluo_data.Spectrum(
    wavelengths=wavelengths,
    values=[80000, 60000, 30000, 10000, 1000],
)
acceptor_emission = fluopy.fluo_data.Spectrum(
    wavelengths=wavelengths,
    values=[0.0, 0.1, 0.5, 1.0, 0.6],
)
acceptor_absorption = fluopy.fluo_data.Spectrum(
    wavelengths=wavelengths,
    values=[1000, 10000, 60000, 90000, 50000],
)

donor_data = fluopy.fluo_data.FluorophoreData(
    QUANTUM_YIELD=0.6,
    FLUORESCENCE_LIFETIME=3e-9,
    emission_spectrum=donor_emission,
    absorption_spectra={"s0": donor_absorption},
)

acceptor_data = fluopy.fluo_data.FluorophoreData(
    QUANTUM_YIELD=0.5,
    FLUORESCENCE_LIFETIME=4e-9,
    emission_spectrum=acceptor_emission,
    absorption_spectra={"s0": acceptor_absorption},
)

donor = fluopy.fluorophores.Fluorophore(
    name="donor",
    position=[0, 0],
    constants=donor_data,
)
acceptor = fluopy.fluorophores.Fluorophore(
    name="acceptor",
    position=[5, 0],
    constants=acceptor_data,
)

fluorophore_system = fluopy.fluorophores.FluorophoreSystem([donor, acceptor])
transitions = fluorophore_system.load_transitions(
    wavelength=550,
    energy_transfer=True,
    energy_transfer_parameters={
        "dipole_orientation_factor": 2 / 3,
        "refractive_index": 1.33,
    },
)
transition_set = fluopy.transitions.TransitionSet(
    transitions=transitions,
    fluorophore_system=fluorophore_system,
)

transition_set.transition_df[["abbreviation", "initial_state", "final_state", "rate"]]

                                          abbreviation  ...          rate
Fluorophore                      identity               ...
donor                            0                 EXC  ...  6.351876e+05
                                 1                 FLU  ...  2.000000e+08
                                 2                  IC  ...  1.333333e+08
D: donor, A: acceptor, dist: 5.0 3                FRET  ...  1.404902e+09
acceptor                         4                 EXC  ...  1.270375e+06
                                 5                 FLU  ...  1.250000e+08
                                 6                  IC  ...  1.250000e+08
D: acceptor, A: donor, dist: 5.0 7                FRET  ...  2.333100e+08

[8 rows x 4 columns]

## Add a custom outcome to a supported FRET channel

The include parameter assigns part of a calculated FRET rate to a custom
TransitionType. It supports the acceptor absorption channels s0, s1, t1, cis,
and off. Included transition types must use TransitionMechanism.FRET.

For the s0 channel below, a factor of 0.2 assigns 20% of the transfer rate to
S1_S0 → S0_T1 and leaves 80% for standard FRET. These are fractions of the
calculated transfer rate; observed event frequencies also depend on competing
processes and state availability. The output table shows the rate split.

include applies to all eligible ordered pairs, including the reverse direction
in this system. Both fluorophores therefore receive a T1-to-S0 recovery rate
through ISC_TS_RATE. include only creates the transfer transitions; relaxation
from their final states must be supplied separately.

In [7]:
import fluopy

wavelengths = [500, 525, 550, 575, 600]
donor_data = fluopy.fluo_data.FluorophoreData(
    QUANTUM_YIELD=0.6,
    FLUORESCENCE_LIFETIME=3e-9,
    ISC_TS_RATE=1e6,
    emission_spectrum=fluopy.fluo_data.Spectrum(
        wavelengths=wavelengths,
        values=[0.0, 0.4, 1.0, 0.6, 0.1],
    ),
    absorption_spectra={
        "s0": fluopy.fluo_data.Spectrum(
            wavelengths=wavelengths,
            values=[80000, 60000, 30000, 10000, 1000],
        )
    },
)
acceptor_data = fluopy.fluo_data.FluorophoreData(
    QUANTUM_YIELD=0.5,
    FLUORESCENCE_LIFETIME=4e-9,
    ISC_TS_RATE=1e6,
    emission_spectrum=fluopy.fluo_data.Spectrum(
        wavelengths=wavelengths,
        values=[0.0, 0.1, 0.5, 1.0, 0.6],
    ),
    absorption_spectra={
        "s0": fluopy.fluo_data.Spectrum(
            wavelengths=wavelengths,
            values=[1000, 10000, 60000, 90000, 50000],
        )
    },
)

donor = fluopy.fluorophores.Fluorophore(
    name="donor", position=[0, 0], constants=donor_data
)
acceptor = fluopy.fluorophores.Fluorophore(
    name="acceptor", position=[5, 0], constants=acceptor_data
)
fluorophore_system = fluopy.fluorophores.FluorophoreSystem([donor, acceptor])

triplet_transfer = fluopy.transitions.TransitionType(
    abbreviation="TET",
    initial_state=fluopy.transitions.PairedState.S1_S0,
    final_state=fluopy.transitions.PairedState.S0_T1,
    photon=False,
    mechanism=fluopy.transitions.TransitionMechanism.FRET,
)
transitions = fluorophore_system.load_transitions(
    wavelength=550,
    energy_transfer=True,
    energy_transfer_parameters={
        "dipole_orientation_factor": 2 / 3,
        "refractive_index": 1.33,
        "include": {
            "s0": [(triplet_transfer, 0.2)],
        },
    },
)

transition_set = fluopy.transitions.TransitionSet(
    transitions=transitions,
    fluorophore_system=fluorophore_system,
)

rate_split = transition_set.transition_df.loc[
    transition_set.transition_df["abbreviation"].isin(["FRET", "TET"]),
    ["abbreviation", "rate"],
].copy()
rate_split["fraction_of_transfer_rate"] = rate_split["rate"] / rate_split.groupby(
    level=0
)["rate"].transform("sum")
rate_split

                                          abbreviation  ...  fraction_of_transfer_rate
Fluorophore                      identity               ...
D: donor, A: acceptor, dist: 5.0 4                 TET  ...                        0.2
                                 5                FRET  ...                        0.8
D: acceptor, A: donor, dist: 5.0 10                TET  ...                        0.2
                                 11               FRET  ...                        0.8

[4 rows x 3 columns]

## Define FRET involving a custom acceptor state

derive_fret_transitions(), used by FluorophoreSystem.load_transitions(), recognizes
the built-in absorption channels s0, s1, t1, cis, and off. Adding a spectrum with
another key does not automatically define a new state or transfer channel.

For a custom state, calculate the FRET rate with
fluopy.transitions.derive_energy_transfer_rate(), then construct the paired
TransitionType and Transition manually. This helper uses the FRET spectral rate
law, so the custom transition also uses TransitionMechanism.FRET.

Here the acceptor first enters DARK. Absorption from DARK allows transfer from
an excited donor to form DARK_EXCITED, which relaxes to S0. The dark_absorption
spectrum describes absorption from the initial DARK state; the paired states
define the transfer's outcome.

In [8]:
import fluopy

wavelengths = [500, 525, 550, 575, 600]
donor_emission = fluopy.fluo_data.Spectrum(
    wavelengths=wavelengths,
    values=[0.0, 0.4, 1.0, 0.6, 0.1],
)
donor_absorption = fluopy.fluo_data.Spectrum(
    wavelengths=wavelengths,
    values=[80000, 60000, 30000, 10000, 1000],
)
acceptor_emission = fluopy.fluo_data.Spectrum(
    wavelengths=wavelengths,
    values=[0.0, 0.1, 0.5, 1.0, 0.6],
)
acceptor_s0_absorption = fluopy.fluo_data.Spectrum(
    wavelengths=wavelengths,
    values=[1000, 10000, 60000, 90000, 50000],
)
dark_absorption = fluopy.fluo_data.Spectrum(
    wavelengths=wavelengths,
    values=[5000, 20000, 70000, 40000, 5000],
)

donor_data = fluopy.fluo_data.FluorophoreData(
    QUANTUM_YIELD=0.6,
    FLUORESCENCE_LIFETIME=3e-9,
    emission_spectrum=donor_emission,
    absorption_spectra={"s0": donor_absorption},
)
acceptor_data = fluopy.fluo_data.FluorophoreData(
    QUANTUM_YIELD=0.5,
    FLUORESCENCE_LIFETIME=4e-9,
    emission_spectrum=acceptor_emission,
    absorption_spectra={
        "s0": acceptor_s0_absorption,
        "dark": dark_absorption,
    },
)

donor = fluopy.fluorophores.Fluorophore(
    name="donor", position=[0, 0], constants=donor_data
)
acceptor = fluopy.fluorophores.Fluorophore(
    name="acceptor", position=[5, 0], constants=acceptor_data
)
fluorophore_system = fluopy.fluorophores.FluorophoreSystem([donor, acceptor])

dark = fluopy.transitions.SingleState(name="DARK", value=10)
dark_excited = fluopy.transitions.SingleState(name="DARK_EXCITED", value=11)
dark_formation = fluopy.transitions.TransitionType(
    abbreviation="DARK_FORM",
    initial_state=fluopy.transitions.SingleState.S0,
    final_state=dark,
    photon=False,
)
dark_relaxation = fluopy.transitions.TransitionType(
    abbreviation="DARK_RELAX",
    initial_state=dark_excited,
    final_state=fluopy.transitions.SingleState.S0,
    photon=False,
)
initial_pair = fluopy.transitions.PairedState(
    name="S1_DARK",
    donor=fluopy.transitions.SingleState.S1,
    acceptor=dark,
)
final_pair = fluopy.transitions.PairedState(
    name="S0_DARK_EXCITED",
    donor=fluopy.transitions.SingleState.S0,
    acceptor=dark_excited,
)
custom_et = fluopy.transitions.TransitionType(
    abbreviation="DARK_ET",
    initial_state=initial_pair,
    final_state=final_pair,
    photon=False,
    mechanism=fluopy.transitions.TransitionMechanism.FRET,
)

transitions = fluorophore_system.load_transitions(
    wavelength=550,
    energy_transfer=False,
)
donor_id = fluorophore_system.get_identity(donor)
acceptor_id = fluorophore_system.get_identity(acceptor)
transitions[acceptor.name].extend(
    [
        fluopy.transitions.Transition(
            dark_formation, rate=1e3, fluorophore_ids=[acceptor_id]
        ),
        fluopy.transitions.Transition(
            dark_relaxation, rate=1e4, fluorophore_ids=[acceptor_id]
        ),
    ]
)

pair = (donor_id, acceptor_id)
distance = fluorophore_system.distances[pair]
rate = fluopy.transitions.derive_energy_transfer_rate(
    donor_data=donor.constants,
    acceptor_absorption=dark_absorption,
    distance=distance,
)

transition_key = f"D: {donor.name}, A: {acceptor.name}, dist: {distance}"
transitions.setdefault(transition_key, []).append(
    fluopy.transitions.Transition(
        transition_type=custom_et,
        rate=rate,
        fluorophore_ids=[pair],
    )
)
transition_set = fluopy.transitions.TransitionSet(
    transitions=transitions,
    fluorophore_system=fluorophore_system,
)

transition_set.transition_df[["abbreviation", "initial_state", "final_state", "rate"]]

                                          abbreviation  ...          rate
Fluorophore                      identity               ...
donor                            0                 EXC  ...  6.351876e+05
                                 1                 FLU  ...  2.000000e+08
                                 2                  IC  ...  1.333333e+08
acceptor                         3                 EXC  ...  1.270375e+06
                                 4                 FLU  ...  1.250000e+08
                                 5                  IC  ...  1.250000e+08
                                 6           DARK_FORM  ...  1.000000e+03
                                 7          DARK_RELAX  ...  1.000000e+04
D: donor, A: acceptor, dist: 5.0 8             DARK_ET  ...  1.130020e+09

[9 rows x 4 columns]

## Optional: events with zero, one, or two state changes

A single-state transition can leave its fluorophore unchanged. A paired
transition can change both components, only one, or neither. Every such
event advances simulation time, but a state residence interval ends only
when that state changes.

This artificial model includes ordinary excitation and emission, a single-state
self-transition, and all four paired outcomes. Its rates and EVENT mechanism
name are illustrative. The table compares event occurrences with the number
of components changed per event; SELF and NONE change zero, FIRST and SECOND
change one, and BOTH changes two. Counts fluctuate between realizations.

See [Interpreting events and statistics](../../source/model_conventions.rst)
for the counting conventions and limits of the analysis and prediction methods.

In [ ]:
import numpy as np
import pandas as pd

from fluopy import fluo_data as fd
from fluopy import fluorophores as fl
from fluopy import simulation as si
from fluopy import transitions as tr

data = fd.FluorophoreData()
system = fl.FluorophoreSystem(
    [
        fl.Fluorophore("first", [0, 0], constants=data),
        fl.Fluorophore("second", [5, 0], constants=data),
    ]
)
self_event = tr.TransitionType("SELF", tr.SingleState.S0, tr.SingleState.S0, False)
both = tr.TransitionType(
    "BOTH", tr.PairedState.S0_S0, tr.PairedState.S1_S1, False, "EVENT"
)
first = tr.TransitionType(
    "FIRST", tr.PairedState.S0_S0, tr.PairedState.S1_S0, False, "EVENT"
)
second = tr.TransitionType(
    "SECOND", tr.PairedState.S0_S0, tr.PairedState.S0_S1, False, "EVENT"
)
neither = tr.TransitionType(
    "NONE", tr.PairedState.S0_S0, tr.PairedState.S0_S0, False, "EVENT"
)
model = tr.TransitionSet(
    {
        "first": [
            tr.Transition(tr.TransitionType.EXCITATION, 3, [0]),
            tr.Transition(tr.TransitionType.FLUORESCENT_EMISSION, 4, [0]),
            tr.Transition(self_event, 2, [0]),
        ],
        "second": [
            tr.Transition(tr.TransitionType.EXCITATION, 3, [1]),
            tr.Transition(tr.TransitionType.FLUORESCENT_EMISSION, 4, [1]),
        ],
        "D: first, A: second, dist: 5.0": [
            tr.Transition(both, 1, [(0, 1)]),
            tr.Transition(first, 1, [(0, 1)]),
            tr.Transition(second, 1, [(0, 1)]),
            tr.Transition(neither, 1, [(0, 1)]),
        ],
    },
    system,
)
simulation = si.Simulation(model)
simulation.run(size=500, seed=51, warn_precision=False)
combined = model.combined_state_transitions_df
events = pd.DataFrame(
    {
        "event": combined.loc[simulation.transition_series, "abbreviation"].to_numpy(),
        "changed_components": np.count_nonzero(
            np.diff(simulation.state_series, axis=1), axis=0
        ),
    }
)
events.groupby("event").agg(
    occurrences=("changed_components", "size"),
    changed_components=("changed_components", "max"),
)

        occurrences  changed_components
event
BOTH             15                   2
EXC             170                   1
FIRST            15                   1
FLU             222                   1
NONE             15                   0
SECOND            8                   1
SELF             55                   0

## Input requirements

- Spectrum wavelengths are in nm and must be finite and strictly increasing.
  Values must be finite and non-negative, with at least two wavelength–value pairs.
- Absorption values are absolute molar extinction coefficients in 1/(M cm).
  Emission intensities may be relative; FRET calculations normalize the donor
  emission spectrum.
- Positions and transfer distances are in nm, lifetimes in seconds, and
  transition rates in 1/s.
- Individual absorption cross sections are in cm² and apply at their specified
  excitation wavelength. FRET calculations use absorption spectra.

The resulting TransitionSet can be passed to Simulation or, for supported
systems, Prediction as in the introductory tutorial.