# Tutorial FluorophoreSystem

### Naming convention
|name|meaning|
|---|---|
|single state|photophysical state|
|joined state|combinations of single states for each fluorophore|
|unique transition|description of each photophysical transition|
|joined transition|change in joined state|
|emission|fluorescent emission|
|event|detected emission|
|resample / deltat|frame integration time, $\tau_{min}$, lag time$_{min}$|

### Handling of multiple possible transitions
Example: The transition between first excited state $S_1$ and ground state $S_0$ can be via fluorescence or via internal/external conversion followed by vibrational relaxation.

Strategy: 
- effected transition rates are added in initialize.construct_transition_matrices
- the rate used in the algorithm is hence dependent on both transitions
- to later discriminate between the two transitions:
    - process.multiple_transitions to create cumulative sum of the effected transitions
    - process.generate_transition_series inserts random number into cumulative sum

In [1]:
#user = r"\SagixOffice"  # HomeOffice
user = r"\vie43sq"  # University
import sys
sys.path.append(rf"C:\Users{user}\OneDrive - Universität Würzburg\GitHub\Photoswitching")

import numpy as np
import pandas as pd
import src.fluorophore_systems as fs
import src.miscellaneous as mi

%load_ext autoreload
%autoreload 2

C:\Users\vie43sq\Miniconda3\envs\MarkovModels\lib\site-packages\pycorrelate\pycorrelate.py:118: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def ucorrelate(t, u, maxlag=None):

In [2]:
transitions = [['S0_S1', 7e6, "excitation", "EXC", False],  
         ['S1_S0', 1e9, "fluorescent emission", "FLU", True], 
         ['S1_T1', 1e6, "intersystem crossing ST", "ISCST", False],   
         ['T1_S0', 5e5, "intersystem crossing TS", "ISCTS", False],
         ['S1_S0', 1e9, "internal conversion S", "ICS", False],
        ['S1_S0__S0_S1', 1e10, "energy transfer", "FRET", False]]

## Initialize object

In [7]:
system = fs.FluorophoreSystem(number_fluorophores=2, distances=1, transitions=transitions)

['S0', 'S0']
S1
['S0', 'S1']
S1
['S0', 'T1']
S1
['S1', 'S0']
S1
['S1', 'S1']
S1
['S1', 'T1']
S1
['T1', 'S0']
S1
['T1', 'S1']
S1
['T1', 'T1']
S1
['S0', 'S0']
S1
['S0', 'S1']
S1
['S0', 'T1']
S1
['S1', 'S0']
S1
['S1', 'S1']
S1
['S1', 'T1']
S1
['T1', 'S0']
S1
['T1', 'S1']
S1
['T1', 'T1']
S1
['S0', 'S0']
S1
['S0', 'S1']
S1
['S0', 'T1']
S1
['S1', 'S0']
S1
['S1', 'S1']
S1
['S1', 'T1']
S1
['T1', 'S0']
S1
['T1', 'S1']
S1
['T1', 'T1']
S1
['S0', 'S0']
S1
['S0', 'S1']
S1
['S0', 'T1']
S1
['S1', 'S0']
S1
['S1', 'S1']
S1
['S1', 'T1']
S1
['T1', 'S0']
S1
['T1', 'S1']
S1
['T1', 'T1']
S1
['S0', 'S0']
S1
['S0', 'S1']
S1
['S0', 'T1']
S1
['S1', 'S0']
S1
['S1', 'S1']
S1
['S1', 'T1']
S1
['T1', 'S0']
S1
['T1', 'S1']
S1
['T1', 'T1']
S1
['S0', 'S0']
S1
['S0', 'S1']
S1
['S0', 'T1']
S1
['S1', 'S0']
S1
['S1', 'S1']
S1
['S1', 'T1']
S1
['T1', 'S0']
S1
['T1', 'S1']
S1
['T1', 'T1']
S1
['S0', 'S0']
S1
['S0', 'S1']
S1
['S0', 'T1']
S1
['S1', 'S0']
S1
['S1', 'S1']
S1
['S1', 'T1']
S1
['T1', 'S0']
S1
['T1', 'S1']
S1
['T1', 'T1']
S1
['S0', 'S0']
S1
['S0', 'S1']
S1
['S0', 'T1']
S1
['S1', 'S0']
S1
['S1', 'S1']
S1
['S1', 'T1']
S1
['T1', 'S0']
S1
['T1', 'S1']
S1
['T1', 'T1']
S1
['S0', 'S0']
S1
['S0', 'S1']
S1
['S0', 'T1']
S1
['S1', 'S0']
S1
['S1', 'S1']
S1
['S1', 'T1']
S1
['T1', 'S0']
S1
['T1', 'S1']
S1
['T1', 'T1']
S1
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
T1
['S0', 'S1']
T1
['S0', 'T1']
T1
['S1', 'S0']
T1
['S1', 'S1']
T1
['S1', 'T1']
T1
['T1', 'S0']
T1
['T1', 'S1']
T1
['T1', 'T1']
T1
['S0', 'S0']
T1
['S0', 'S1']
T1
['S0', 'T1']
T1
['S1', 'S0']
T1
['S1', 'S1']
T1
['S1', 'T1']
T1
['T1', 'S0']
T1
['T1', 'S1']
T1
['T1', 'T1']
T1
['S0', 'S0']
T1
['S0', 'S1']
T1
['S0', 'T1']
T1
['S1', 'S0']
T1
['S1', 'S1']
T1
['S1', 'T1']
T1
['T1', 'S0']
T1
['T1', 'S1']
T1
['T1', 'T1']
T1
['S0', 'S0']
T1
['S0', 'S1']
T1
['S0', 'T1']
T1
['S1', 'S0']
T1
['S1', 'S1']
T1
['S1', 'T1']
T1
['T1', 'S0']
T1
['T1', 'S1']
T1
['T1', 'T1']
T1
['S0', 'S0']
T1
['S0', 'S1']
T1
['S0', 'T1']
T1
['S1', 'S0']
T1
['S1', 'S1']
T1
['S1', 'T1']
T1
['T1', 'S0']
T1
['T1', 'S1']
T1
['T1', 'T1']
T1
['S0', 'S0']
T1
['S0', 'S1']
T1
['S0', 'T1']
T1
['S1', 'S0']
T1
['S1', 'S1']
T1
['S1', 'T1']
T1
['T1', 'S0']
T1
['T1', 'S1']
T1
['T1', 'T1']
T1
['S0', 'S0']
T1
['S0', 'S1']
T1
['S0', 'T1']
T1
['S1', 'S0']
T1
['S1', 'S1']
T1
['S1', 'T1']
T1
['T1', 'S0']
T1
['T1', 'S1']
T1
['T1', 'T1']
T1
['S0', 'S0']
T1
['S0', 'S1']
T1
['S0', 'T1']
T1
['S1', 'S0']
T1
['S1', 'S1']
T1
['S1', 'T1']
T1
['T1', 'S0']
T1
['T1', 'S1']
T1
['T1', 'T1']
T1
['S0', 'S0']
T1
['S0', 'S1']
T1
['S0', 'T1']
T1
['S1', 'S0']
T1
['S1', 'S1']
T1
['S1', 'T1']
T1
['T1', 'S0']
T1
['T1', 'S1']
T1
['T1', 'T1']
T1
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0
['S0', 'S0']
S0
['S0', 'S1']
S0
['S0', 'T1']
S0
['S1', 'S0']
S0
['S1', 'S1']
S0
['S1', 'T1']
S0
['T1', 'S0']
S0
['T1', 'S1']
S0
['T1', 'T1']
S0

In [4]:
system.single_states

{0: 'S0', 1: 'S1', 2: 'T1'}

In [5]:
system.unique_transitions

            name     rate             trivial_name abbreviation  fluorescence
id
0          S0_S1 7.00e+06               excitation          EXC         False
1          S1_S0 1.00e+09     fluorescent emission          FLU          True
2          S1_T1 1.00e+06  intersystem crossing ST        ISCST         False
3          T1_S0 5.00e+05  intersystem crossing TS        ISCTS         False
4          S1_S0 1.00e+09    internal conversion S          ICS         False
5   S1_S0__S0_S1 1.00e+10          energy transfer         FRET         False

In [6]:
system.joined_states

     name single_states single_state_counter  absorbing
id
0   S0_S0        [0, 0]            [2, 0, 0]      False
1   S0_S1        [0, 1]            [1, 1, 0]      False
2   S0_T1        [0, 2]            [1, 0, 1]      False
3   S1_S0        [1, 0]            [1, 1, 0]      False
4   S1_S1        [1, 1]            [0, 2, 0]      False
5   S1_T1        [1, 2]            [0, 1, 1]      False
6   T1_S0        [2, 0]            [1, 0, 1]      False
7   T1_S1        [2, 1]            [0, 1, 1]      False
8   T1_T1        [2, 2]            [0, 0, 2]      False

In [7]:
system.joined_transitions

,name,joined_states_id,unique_transition_id,rate,trivial_name,fluorescence
id,,,,,,
0,S0_S0__S0_S1,"(0, 1)",0,7.00e+06,excitation,False
1,S0_S0__S1_S0,"(0, 3)",0,7.00e+06,excitation,False
2,S0_S1__S1_S1,"(1, 4)",0,7.00e+06,excitation,False
3,S0_T1__S1_T1,"(2, 5)",0,7.00e+06,excitation,False
4,S1_S0__S1_S1,"(3, 4)",0,7.00e+06,excitation,False
5,T1_S0__T1_S1,"(6, 7)",0,7.00e+06,excitation,False
6,S0_S1__S0_S0,"(1, 0)",1,1.00e+09,fluorescent emission,True
7,S1_S0__S0_S0,"(3, 0)",1,1.00e+09,fluorescent emission,True
8,S1_S1__S0_S1,"(4, 1)",1,1.00e+09,fluorescent emission,True
9,S1_S1__S1_S0,"(4, 3)",1,1.00e+09,fluorescent emission,True
10,S1_T1__S0_T1,"(5, 2)",1,1.00e+09,fluorescent emission,True
11,T1_S1__T1_S0,"(7, 6)",1,1.00e+09,fluorescent emission,True
12,S0_S1__S0_T1,"(1, 2)",2,1.00e+06,intersystem crossing ST,False
13,S1_S0__T1_S0,"(3, 6)",2,1.00e+06,intersystem crossing ST,False
14,S1_S1__S1_T1,"(4, 5)",2,1.00e+06,intersystem crossing ST,False
15,S1_S1__T1_S1,"(4, 7)",2,1.00e+06,intersystem crossing ST,False
16,S1_T1__T1_T1,"(5, 8)",2,1.00e+06,intersystem crossing ST,False
17,T1_S1__T1_T1,"(7, 8)",2,1.00e+06,intersystem crossing ST,False
18,S0_T1__S0_S0,"(2, 0)",3,5.00e+05,intersystem crossing TS,False
19,S1_T1__S1_S0,"(5, 3)",3,5.00e+05,intersystem crossing TS,False
20,T1_S0__S0_S0,"(6, 0)",3,5.00e+05,intersystem crossing TS,False
21,T1_S1__S0_S1,"(7, 1)",3,5.00e+05,intersystem crossing TS,False
22,T1_T1__S0_T1,"(8, 2)",3,5.00e+05,intersystem crossing TS,False
23,T1_T1__T1_S0,"(8, 6)",3,5.00e+05,intersystem crossing TS,False
24,S0_S1__S0_S0,"(1, 0)",4,1.00e+09,internal conversion S,False
25,S1_S0__S0_S0,"(3, 0)",4,1.00e+09,internal conversion S,False
26,S1_S1__S0_S1,"(4, 1)",4,1.00e+09,internal conversion S,False
27,S1_S1__S1_S0,"(4, 3)",4,1.00e+09,internal conversion S,False
28,S1_T1__S0_T1,"(5, 2)",4,1.00e+09,internal conversion S,False
29,T1_S1__T1_S0,"(7, 6)",4,1.00e+09,internal conversion S,False
30,S0_S1__S1_S0,"(1, 3)",5,1.00e+10,energy transfer,False
31,S1_S0__S0_S1,"(3, 1)",5,1.00e+10,energy transfer,False

In [8]:
system.transition_matrix

array([[0.00000000e+00, 5.00000000e-01, 0.00000000e+00, 5.00000000e-01,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [1.66555630e-01, 0.00000000e+00, 8.32778148e-05, 8.32778148e-01,
        5.82944704e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [6.66666667e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 9.33333333e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [1.66555630e-01, 8.32778148e-01, 0.00000000e+00, 0.00000000e+00,
        5.82944704e-04, 0.00000000e+00, 8.32778148e-05, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 4.99750125e-01, 0.00000000e+00, 4.99750125e-01,
        0.00000000e+00, 2.49875062e-04, 0.00000000e+00, 2.49875062e-04,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 9.99250562e-01, 2.49812641e-04,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.99625281e-04],
       [6.66666667e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 9.33333333e-01,
        0.00000000e+00],
       [0.00000000e+00, 2.49812641e-04, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 9.99250562e-01, 0.00000000e+00,
        4.99625281e-04],
       [0.00000000e+00, 0.00000000e+00, 5.00000000e-01, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 5.00000000e-01, 0.00000000e+00,
        0.00000000e+00]])

In [9]:
system.row_sums

array([1.4000e+07, 1.2008e+10, 7.5000e+06, 1.2008e+10, 4.0020e+09,
       2.0015e+09, 7.5000e+06, 2.0015e+09, 1.0000e+06])

In [10]:
system.graph

In [11]:
system.plot

## Method simulate()

In [12]:
system.simulate(n_steps=500, seed=100)

In [13]:
system.time_series

array([0.00000000e+00, 1.28818253e-08, 1.29852398e-08, 1.48923019e-08,
       1.49119046e-08, 1.49430290e-08, 1.49445858e-08, 1.49831593e-08,
       1.50257119e-08, 1.50260643e-08, 1.50477197e-08, 1.50479136e-08,
       1.51255702e-08, 1.51379196e-08, 1.51686484e-08, 1.52471137e-08,
       4.87619684e-08, 4.88696081e-08, 4.92211687e-08, 4.94398198e-08,
       4.94901303e-08, 4.94938795e-08, 4.95508229e-08, 4.95858114e-08,
       4.97807293e-08, 4.98247305e-08, 4.98676681e-08, 9.12770726e-08,
       9.13222945e-08, 9.13508611e-08, 1.71661272e-07, 1.71685449e-07,
       1.71748982e-07, 2.30050936e-07, 2.30150378e-07, 2.30179296e-07,
       2.30265112e-07, 2.30321151e-07, 2.30413394e-07, 2.30447646e-07,
       2.30493707e-07, 2.30514407e-07, 2.30620920e-07, 2.30647140e-07,
       2.30787839e-07, 2.30810655e-07, 2.30811119e-07, 2.30829121e-07,
       2.30831406e-07, 2.30843904e-07, 2.30947495e-07, 2.31052302e-07,
       2.31286900e-07, 2.31555325e-07, 2.31581929e-07, 2.39779678e-07,
       2.39787565e-07, 2.39822483e-07, 2.39833154e-07, 2.39942044e-07,
       2.39942659e-07, 2.39983399e-07, 2.40014802e-07, 2.40112520e-07,
       2.40208500e-07, 2.40489946e-07, 2.40565313e-07, 2.40612339e-07,
       2.40621871e-07, 2.40625470e-07, 2.40713450e-07, 2.40753305e-07,
       2.40938813e-07, 2.41078914e-07, 2.41088590e-07, 2.41344923e-07,
       2.41357388e-07, 2.41429932e-07, 2.41432295e-07, 2.41480849e-07,
       2.41494196e-07, 2.41501169e-07, 2.41594300e-07, 2.41618724e-07,
       2.41825240e-07, 2.42023819e-07, 2.42042440e-07, 2.42149692e-07,
       2.89260873e-07, 2.89265427e-07, 2.89343474e-07, 2.89360092e-07,
       2.89377788e-07, 2.89542618e-07, 2.89743046e-07, 2.89771733e-07,
       2.89857501e-07, 2.89926496e-07, 2.89967286e-07, 2.90094217e-07,
       2.90235446e-07, 2.90339462e-07, 2.90370127e-07, 2.90429563e-07,
       3.08701094e-07, 3.08750555e-07, 3.08784952e-07, 4.31813570e-07,
       4.31843168e-07, 4.31967425e-07, 4.32174758e-07, 4.32194447e-07,
       4.32238455e-07, 4.32326636e-07, 4.63630849e-07, 4.63652156e-07,
       5.27801624e-07, 5.27870238e-07, 5.71926205e-07, 5.72265077e-07,
       5.72406697e-07, 5.72436464e-07, 5.72455588e-07, 5.72522113e-07,
       5.72558881e-07, 5.72706926e-07, 5.72733089e-07, 5.72836682e-07,
       5.72867847e-07, 5.72886721e-07, 5.80878339e-07, 5.81005500e-07,
       5.81027126e-07, 5.81092096e-07, 5.81094586e-07, 5.81268575e-07,
       5.81284970e-07, 5.81348881e-07, 5.81352912e-07, 5.81610113e-07,
       6.38755151e-07, 6.38795944e-07, 6.38938393e-07, 6.48877289e-07,
       6.48962673e-07, 6.48981491e-07, 6.49002193e-07, 6.49075518e-07,
       6.73677754e-07, 6.73808487e-07, 6.73854064e-07, 6.89822715e-07,
       6.89922270e-07, 6.89923632e-07, 6.89961224e-07, 6.90017106e-07,
       6.90040403e-07, 6.90092301e-07, 7.05676861e-07, 7.05745681e-07,
       7.05892541e-07, 7.05960459e-07, 7.05994961e-07, 7.06153749e-07,
       7.06175209e-07, 7.06345700e-07, 7.43422569e-07, 7.43450683e-07,
       7.43453978e-07, 7.43621218e-07, 7.43652006e-07, 7.43681743e-07,
       7.43693626e-07, 7.43770541e-07, 7.43841438e-07, 7.43900791e-07,
       7.44059300e-07, 7.44113409e-07, 7.44127006e-07, 7.44180863e-07,
       7.44335393e-07, 7.44349954e-07, 7.44553967e-07, 7.44665027e-07,
       7.44792248e-07, 7.54624583e-07, 7.54857042e-07, 7.54883829e-07,
       7.54887580e-07, 7.54976698e-07, 7.54988725e-07, 7.55010441e-07,
       7.55107101e-07, 7.93283344e-07, 7.93462170e-07, 7.93488385e-07,
       7.93503998e-07, 7.93586615e-07, 7.93617652e-07, 7.93632774e-07,
       7.93755842e-07, 7.93994674e-07, 8.46942605e-07, 8.46944417e-07,
       9.29687384e-07, 9.29770405e-07, 1.08183113e-06, 1.08198528e-06,
       1.08205175e-06, 1.08206208e-06, 1.08208656e-06, 1.08213488e-06,
       1.08214065e-06, 1.08218334e-06, 1.08221544e-06, 1.08232106e-06,
       1.08237743e-06, 1.16440889e-06, 1.16444415e-06, 1.16477070e-06,
       1.16499197e-06, 1.16514400e-06, 1.16519442e-06, 1.16526947e-06,
       1.16537256e-06, 1.16539920e-06, 1.16540070e-06, 1.16540417e-06,
       1.16548280e-06, 1.16556150e-06, 1.16560518e-06, 1.16584881e-06,
       1.16596599e-06, 1.16596792e-06, 1.16609971e-06, 1.16617931e-06,
       1.16634538e-06, 1.16648013e-06, 1.16672600e-06, 1.16689487e-06,
       1.16695838e-06, 1.16700358e-06, 1.16706016e-06, 1.16707350e-06,
       1.16709333e-06, 1.16715597e-06, 1.16718081e-06, 1.17871648e-06,
       1.17872624e-06, 1.17879866e-06, 1.17890989e-06, 1.17899302e-06,
       1.17907965e-06, 1.19294431e-06, 1.19297152e-06, 1.19313222e-06,
       1.19338637e-06, 1.19339466e-06, 1.19342989e-06, 1.19344373e-06,
       1.23473650e-06, 1.23482703e-06, 1.23484189e-06, 1.23490792e-06,
       1.23502643e-06, 1.26672422e-06, 1.26677145e-06, 1.26700817e-06,
       1.26709028e-06, 1.35917098e-06, 1.35921702e-06, 1.50065346e-06,
       1.50083266e-06, 1.50085152e-06, 1.50095257e-06, 1.50118262e-06,
       1.50120836e-06, 1.50121770e-06, 1.50149711e-06, 1.50159422e-06,
       1.50160096e-06, 1.50172508e-06, 1.50172692e-06, 1.50196074e-06,
       1.50196748e-06, 1.65465612e-06, 1.65469136e-06, 1.65473528e-06,
       1.70419890e-06, 1.70421164e-06, 1.70430256e-06, 1.70431825e-06,
       1.70440893e-06, 1.73794751e-06, 1.73807876e-06, 1.73814437e-06,
       1.85372116e-06, 1.85376170e-06, 1.95103586e-06, 1.95124731e-06,
       1.95143995e-06, 1.95154865e-06, 1.95163202e-06, 1.95164444e-06,
       1.95178587e-06, 1.95181443e-06, 1.95193399e-06, 1.95198467e-06,
       1.95208062e-06, 1.95211741e-06, 1.95222576e-06, 1.95233811e-06,
       1.95237174e-06, 1.95247487e-06, 1.95249115e-06, 1.95261786e-06,
       2.09228537e-06, 2.09254448e-06, 2.10522025e-06, 2.10528686e-06,
       2.22733951e-06, 2.22735567e-06, 2.22737055e-06, 2.22738758e-06,
       2.22747064e-06, 2.22757860e-06, 2.22758603e-06, 2.27907971e-06,
       2.27917264e-06, 2.27924172e-06, 2.27924822e-06, 2.27925147e-06,
       2.27926869e-06, 2.27938904e-06, 2.27947804e-06, 2.27948303e-06,
       2.27949605e-06, 2.27962049e-06, 2.27965239e-06, 2.27971172e-06,
       2.27972853e-06, 2.27984229e-06, 2.31776579e-06, 2.31778321e-06,
       2.31784233e-06, 2.31785981e-06, 2.31801434e-06, 2.31802571e-06,
       2.31807294e-06, 2.31807585e-06, 2.31811709e-06, 2.31817933e-06,
       2.43973461e-06, 2.43980735e-06, 2.43985033e-06, 2.44000730e-06,
       2.44005378e-06, 2.44017581e-06, 2.44033046e-06, 2.44036939e-06,
       2.44040515e-06, 2.48833677e-06, 2.48836704e-06, 2.48843332e-06,
       2.48845847e-06, 2.48851104e-06, 2.48851419e-06, 2.48871453e-06,
       2.48874035e-06, 2.48884932e-06, 2.48890684e-06, 2.48899698e-06,
       2.50094772e-06, 2.50110717e-06, 2.50115306e-06, 2.50122449e-06,
       2.50127607e-06, 2.50132981e-06, 2.50157770e-06, 2.52185003e-06,
       2.52188612e-06, 2.52193588e-06, 2.53870790e-06, 2.53873627e-06,
       2.54016233e-06, 2.54028960e-06, 2.54039399e-06, 2.54040441e-06,
       2.54041322e-06, 2.54046282e-06, 2.54046380e-06, 2.54047803e-06,
       2.54056618e-06, 2.54067365e-06, 2.54069195e-06, 2.54071499e-06,
       2.54073272e-06, 2.54074329e-06, 2.54075974e-06, 2.54076306e-06,
       2.54081997e-06, 2.54464162e-06, 2.54471508e-06, 2.54480111e-06,
       2.57262882e-06, 2.57265557e-06, 2.57276347e-06, 2.57276922e-06,
       2.57278909e-06, 2.57283124e-06, 2.57286524e-06, 2.57293548e-06,
       2.57299389e-06, 2.57305020e-06, 2.57305455e-06, 2.57316382e-06,
       2.57325978e-06, 2.57328959e-06, 2.57329020e-06, 2.76934895e-06,
       2.76955377e-06, 2.76956159e-06, 2.76985215e-06, 2.78533186e-06,
       2.78534944e-06, 2.78535630e-06, 2.78536148e-06, 2.78538586e-06,
       2.78543193e-06, 2.78550969e-06, 2.78556447e-06, 2.78567453e-06,
       2.78567833e-06, 2.78576356e-06, 2.78576475e-06, 2.78577899e-06,
       2.78584258e-06, 2.78585833e-06, 2.78595627e-06, 2.78596554e-06,
       2.78604942e-06, 2.78613012e-06, 2.78662764e-06, 2.78675088e-06,
       2.78683447e-06, 2.78683882e-06, 2.92659205e-06, 2.92659357e-06,
       2.92669448e-06, 2.92684920e-06, 2.92687764e-06, 2.92704351e-06,
       2.92709542e-06, 2.92725376e-06, 2.92737007e-06, 2.92737028e-06,
       2.92753504e-06, 3.03632502e-06, 3.03660872e-06, 3.03674997e-06,
       3.03678610e-06, 3.39228098e-06, 3.39229367e-06, 3.39249414e-06,
       3.39251317e-06, 3.39267082e-06, 3.39272008e-06, 3.39276917e-06,
       3.39287263e-06, 3.39298793e-06, 3.39300907e-06, 3.39306685e-06,
       3.39310800e-06, 3.44758802e-06, 3.44773899e-06, 3.44784284e-06,
       3.46117271e-06, 3.46124391e-06, 3.46127290e-06, 3.46136072e-06,
       3.46144439e-06, 3.46149463e-06, 3.46159008e-06, 3.53979052e-06,
       3.53979501e-06, 3.53993471e-06, 3.54003471e-06, 3.54005649e-06,
       3.54011968e-06, 3.54019205e-06, 3.54024387e-06, 3.54033883e-06,
       3.54042788e-06, 3.54047799e-06, 3.54076710e-06, 3.54076934e-06,
       3.54082453e-06, 3.54099174e-06, 3.54104116e-06, 3.62463380e-06,
       3.62492929e-06])

In [14]:
system.time_step_series

array([0.00000000e+00, 1.28818253e-08, 1.03414550e-10, 1.90706206e-09,
       1.96027040e-11, 3.11244153e-11, 1.55685219e-12, 3.85734364e-11,
       4.25526187e-11, 3.52418170e-13, 2.16553651e-11, 1.93888659e-13,
       7.76566709e-11, 1.23493053e-11, 3.07288847e-11, 7.84652686e-11,
       3.35148547e-08, 1.07639753e-10, 3.51560602e-10, 2.18651042e-10,
       5.03105047e-11, 3.74917992e-12, 5.69433996e-11, 3.49885807e-11,
       1.94917848e-10, 4.40012227e-11, 4.29376131e-11, 4.14094045e-08,
       4.52219236e-11, 2.85665554e-11, 8.03104110e-08, 2.41767106e-11,
       6.35333691e-11, 5.83019541e-08, 9.94422541e-11, 2.89179855e-11,
       8.58160159e-11, 5.60382377e-11, 9.22432423e-11, 3.42516695e-11,
       4.60617572e-11, 2.06992919e-11, 1.06513161e-10, 2.62196790e-11,
       1.40699656e-10, 2.28159315e-11, 4.63577060e-13, 1.80024989e-11,
       2.28485178e-12, 1.24981036e-11, 1.03590738e-10, 1.04806808e-10,
       2.34598494e-10, 2.68424366e-10, 2.66047703e-11, 8.19774915e-09,
       7.88610559e-12, 3.49189186e-11, 1.06700709e-11, 1.08890508e-10,
       6.14677684e-13, 4.07405711e-11, 3.14022869e-11, 9.77185142e-11,
       9.59798727e-11, 2.81446225e-10, 7.53669305e-11, 4.70260084e-11,
       9.53182181e-12, 3.59950970e-12, 8.79790916e-11, 3.98559050e-11,
       1.85507294e-10, 1.40100943e-10, 9.67654051e-12, 2.56332982e-10,
       1.24652105e-11, 7.25437653e-11, 2.36324721e-12, 4.85532604e-11,
       1.33475663e-11, 6.97261688e-12, 9.31314405e-11, 2.44232350e-11,
       2.06516002e-10, 1.98579101e-10, 1.86210630e-11, 1.07252456e-10,
       4.71111805e-08, 4.55474732e-12, 7.80467718e-11, 1.66181125e-11,
       1.76955797e-11, 1.64829623e-10, 2.00428807e-10, 2.86868024e-11,
       8.57675337e-11, 6.89951985e-11, 4.07902092e-11, 1.26931118e-10,
       1.41228712e-10, 1.04016212e-10, 3.06644081e-11, 5.94361377e-11,
       1.82715312e-08, 4.94614138e-11, 3.43970265e-11, 1.23028618e-07,
       2.95980617e-11, 1.24256868e-10, 2.07332653e-10, 1.96897028e-11,
       4.40080096e-11, 8.81801746e-11, 3.13042131e-08, 2.13075483e-11,
       6.41494681e-08, 6.86139262e-11, 4.40559673e-08, 3.38871636e-10,
       1.41620011e-10, 2.97665341e-11, 1.91240396e-11, 6.65253326e-11,
       3.67678176e-11, 1.48045529e-10, 2.61628559e-11, 1.03592634e-10,
       3.11648975e-11, 1.88741587e-11, 7.99161809e-09, 1.27161050e-10,
       2.16261997e-11, 6.49698424e-11, 2.48971335e-12, 1.73989278e-10,
       1.63946970e-11, 6.39111854e-11, 4.03149801e-12, 2.57200283e-10,
       5.71450386e-08, 4.07928552e-11, 1.42449202e-10, 9.93889579e-09,
       8.53838288e-11, 1.88176499e-11, 2.07028044e-11, 7.33249272e-11,
       2.46022352e-08, 1.30733072e-10, 4.55773404e-11, 1.59686509e-08,
       9.95551705e-11, 1.36222062e-12, 3.75915258e-11, 5.58826542e-11,
       2.32970212e-11, 5.18980947e-11, 1.55845599e-08, 6.88192511e-11,
       1.46860317e-10, 6.79178153e-11, 3.45024952e-11, 1.58788206e-10,
       2.14593526e-11, 1.70491329e-10, 3.70768684e-08, 2.81147200e-11,
       3.29518424e-12, 1.67239111e-10, 3.07882993e-11, 2.97372598e-11,
       1.18826279e-11, 7.69156107e-11, 7.08968427e-11, 5.93532317e-11,
       1.58508824e-10, 5.41082867e-11, 1.35974334e-11, 5.38567098e-11,
       1.54530740e-10, 1.45604112e-11, 2.04013572e-10, 1.11059141e-10,
       1.27221707e-10, 9.83233442e-09, 2.32458894e-10, 2.67876725e-11,
       3.75047246e-12, 8.91179402e-11, 1.20275115e-11, 2.17158159e-11,
       9.66596747e-11, 3.81762436e-08, 1.78825815e-10, 2.62149773e-11,
       1.56131205e-11, 8.26165123e-11, 3.10374866e-11, 1.51218688e-11,
       1.23067679e-10, 2.38831770e-10, 5.29479316e-08, 1.81208923e-12,
       8.27429670e-08, 8.30205988e-11, 1.52060726e-07, 1.54148267e-10,
       6.64732017e-11, 1.03313815e-11, 2.44759815e-11, 4.83162437e-11,
       5.77338898e-12, 4.26858645e-11, 3.21027658e-11, 1.05617546e-10,
       5.63762915e-11, 8.20314610e-08, 3.52552593e-11, 3.26551518e-10,
       2.21269238e-10, 1.52030737e-10, 5.04195850e-11, 7.50527981e-11,
       1.03089147e-10, 2.66357027e-11, 1.50063508e-12, 3.47249499e-12,
       7.86308953e-11, 7.86976421e-11, 4.36842915e-11, 2.43625040e-10,
       1.17186298e-10, 1.92222413e-12, 1.31790158e-10, 7.96031279e-11,
       1.66070140e-10, 1.34746822e-10, 2.45876335e-10, 1.68869103e-10,
       6.35063158e-11, 4.51984880e-11, 5.65798166e-11, 1.33401241e-11,
       1.98318563e-11, 6.26399791e-11, 2.48409470e-11, 1.15356668e-08,
       9.76097720e-12, 7.24187623e-11, 1.11238309e-10, 8.31206543e-11,
       8.66369140e-11, 1.38646559e-08, 2.72114487e-11, 1.60703972e-10,
       2.54147730e-10, 8.28378817e-12, 3.52362820e-11, 1.38399130e-11,
       4.12927693e-08, 9.05326446e-11, 1.48576268e-11, 6.60312627e-11,
       1.18510006e-10, 3.16977912e-08, 4.72217152e-11, 2.36724736e-10,
       8.21069148e-11, 9.20807024e-08, 4.60425143e-11, 1.41436438e-07,
       1.79204368e-10, 1.88549852e-11, 1.01054356e-10, 2.30049978e-10,
       2.57339078e-11, 9.34024367e-12, 2.79410897e-10, 9.71070644e-11,
       6.73944106e-12, 1.24122050e-10, 1.84787899e-12, 2.33813334e-10,
       6.73799890e-12, 1.52688639e-07, 3.52441857e-11, 4.39188551e-11,
       4.94636205e-08, 1.27456692e-11, 9.09197171e-11, 1.56825090e-11,
       9.06863078e-11, 3.35385751e-08, 1.31252700e-10, 6.56123075e-11,
       1.15576785e-07, 4.05445093e-11, 9.72741547e-08, 2.11451629e-10,
       1.92638329e-10, 1.08699442e-10, 8.33708900e-11, 1.24265734e-11,
       1.41423446e-10, 2.85617957e-11, 1.19565297e-10, 5.06742820e-11,
       9.59515099e-11, 3.67916018e-11, 1.08343065e-10, 1.12353297e-10,
       3.36294409e-11, 1.03131537e-10, 1.62789055e-11, 1.26713971e-10,
       1.39667509e-07, 2.59111791e-10, 1.26757636e-08, 6.66113921e-11,
       1.22052647e-07, 1.61694631e-11, 1.48790119e-11, 1.70247153e-11,
       8.30577182e-11, 1.07959215e-10, 7.43400934e-12, 5.14936813e-08,
       9.29301527e-11, 6.90770148e-11, 6.50049403e-12, 3.24958031e-12,
       1.72244115e-11, 1.20347507e-10, 8.90049243e-11, 4.99017071e-12,
       1.30194963e-11, 1.24438210e-10, 3.18931913e-11, 5.93378110e-11,
       1.68032058e-11, 1.13760625e-10, 3.79234997e-08, 1.74224452e-11,
       5.91226351e-11, 1.74768010e-11, 1.54527527e-10, 1.13755686e-11,
       4.72284721e-11, 2.90561765e-12, 4.12486629e-11, 6.22380478e-11,
       1.21555282e-07, 7.27306383e-11, 4.29883379e-11, 1.56961870e-10,
       4.64875827e-11, 1.22028452e-10, 1.54645416e-10, 3.89300477e-11,
       3.57633080e-11, 4.79316168e-08, 3.02777847e-11, 6.62726478e-11,
       2.51543703e-11, 5.25651370e-11, 3.14879854e-12, 2.00343115e-10,
       2.58178709e-11, 1.08971588e-10, 5.75233229e-11, 9.01336109e-11,
       1.19507430e-08, 1.59453373e-10, 4.58856623e-11, 7.14325705e-11,
       5.15774509e-11, 5.37444394e-11, 2.47884702e-10, 2.02723339e-08,
       3.60927589e-11, 4.97561014e-11, 1.67720245e-08, 2.83697244e-11,
       1.42605172e-09, 1.27276540e-10, 1.04384683e-10, 1.04258864e-11,
       8.80507759e-12, 4.96043218e-11, 9.75804697e-13, 1.42321659e-11,
       8.81454529e-11, 1.07475761e-10, 1.82950161e-11, 2.30462882e-11,
       1.77305540e-11, 1.05645987e-11, 1.64546867e-11, 3.32139825e-12,
       5.69090948e-11, 3.82164437e-09, 7.34628505e-11, 8.60337492e-11,
       2.78277074e-08, 2.67444870e-11, 1.07904578e-10, 5.75317874e-12,
       1.98626765e-11, 4.21527529e-11, 3.40033158e-11, 7.02387853e-11,
       5.84081886e-11, 5.63095660e-11, 4.34681386e-12, 1.09278690e-10,
       9.59536255e-11, 2.98100227e-11, 6.12784601e-13, 1.96058754e-07,
       2.04812307e-10, 7.82681964e-12, 2.90557655e-10, 1.54797110e-08,
       1.75817359e-11, 6.85701731e-12, 5.17938179e-12, 2.43768015e-11,
       4.60697715e-11, 7.77629230e-11, 5.47757131e-11, 1.10065026e-10,
       3.79640042e-12, 8.52310235e-11, 1.19429962e-12, 1.42364285e-11,
       6.35941690e-11, 1.57521864e-11, 9.79376450e-11, 9.27050014e-12,
       8.38787673e-11, 8.07024053e-11, 4.97518270e-10, 1.23240605e-10,
       8.35869890e-11, 4.35383412e-12, 1.39753223e-07, 1.52090687e-12,
       1.00907690e-10, 1.54729308e-10, 2.84389418e-11, 1.65865945e-10,
       5.19129283e-11, 1.58336726e-10, 1.16313312e-10, 2.08651293e-13,
       1.64758983e-10, 1.08789980e-07, 2.83703161e-10, 1.41246842e-10,
       3.61320341e-11, 3.55494882e-07, 1.26831511e-11, 2.00473718e-10,
       1.90326444e-11, 1.57648412e-10, 4.92598328e-11, 4.90869700e-11,
       1.03465641e-10, 1.15299782e-10, 2.11309855e-11, 5.77844889e-11,
       4.11526687e-11, 5.44800146e-08, 1.50972495e-10, 1.03854679e-10,
       1.33298700e-08, 7.12002658e-11, 2.89826701e-11, 8.78213317e-11,
       8.36747123e-11, 5.02387617e-11, 9.54465676e-11, 7.82004399e-08,
       4.49451834e-12, 1.39698652e-10, 9.99986069e-11, 2.17791835e-11,
       6.31861505e-11, 7.23743356e-11, 5.18238866e-11, 9.49569193e-11,
       8.90494573e-11, 5.01070183e-11, 2.89111533e-10, 2.23955008e-12,
       5.51946209e-11, 1.67211114e-10, 4.94161623e-11, 8.35926362e-08,
       2.95494043e-10])

In [15]:
system.state_series

array([0, 3, 0, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 0, 1, 3, 1, 3, 1, 3,
       1, 3, 1, 3, 0, 3, 1, 0, 1, 3, 0, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1,
       3, 1, 3, 1, 3, 1, 3, 1, 4, 1, 0, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3,
       1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 0,
       3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 0, 1, 3, 0, 3, 1, 3,
       1, 3, 1, 0, 1, 0, 3, 0, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 0, 3, 1,
       3, 1, 3, 1, 3, 1, 3, 0, 3, 1, 0, 3, 1, 3, 1, 0, 1, 3, 0, 1, 3, 1,
       3, 1, 3, 0, 1, 3, 1, 3, 1, 3, 1, 0, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1,
       3, 1, 3, 1, 3, 1, 3, 1, 0, 3, 1, 3, 1, 3, 1, 3, 0, 3, 1, 3, 1, 3,
       1, 3, 1, 0, 3, 0, 1, 0, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 0, 1, 3, 1,
       3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 0, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3,
       1, 3, 1, 3, 0, 1, 3, 1, 3, 1, 0, 1, 3, 1, 3, 1, 3, 0, 1, 3, 1, 3,
       0, 1, 3, 1, 0, 3, 0, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 0, 3,
       1, 0, 3, 1, 3, 1, 0, 1, 3, 0, 1, 0, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3,
       1, 3, 1, 3, 1, 3, 1, 0, 3, 0, 1, 0, 1, 3, 1, 3, 1, 3, 0, 3, 1, 3,
       1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 0, 3, 1, 3, 1, 3, 1, 3, 1, 3, 0,
       1, 3, 1, 3, 1, 3, 1, 3, 0, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 0, 1, 3,
       1, 3, 1, 3, 0, 1, 3, 0, 3, 0, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1,
       3, 1, 3, 1, 0, 1, 3, 0, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1,
       0, 3, 1, 3, 0, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3,
       1, 0, 3, 1, 3, 0, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 0, 1, 3, 1, 0, 1,
       3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 0, 1, 3, 0, 1, 3, 1, 3, 1, 3, 0, 3,
       1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 0, 3, 0], dtype=int64)

The total time of simulation in minutes:

In [16]:
system.time_series[-1] / 60

6.04154881773402e-08

## Method process()
Analysis of complete simulation.

In [17]:
system.process()

In [18]:
system.single_state_series

array([[0., 1., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
system.transition_series

array([0, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 4, 0, 5, 1, 0, 5, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 0, 4, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 5, 1, 0, 5, 5, 5,
       5, 5, 4, 0, 4, 0, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 5, 5,
       5, 5, 5, 5, 5, 5, 1, 0, 5, 1, 0, 5, 5, 5, 4, 0, 5, 4, 0, 5, 5, 5,
       5, 5, 4, 0, 5, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5, 5, 5,
       5, 5, 1, 0, 4, 0, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 4, 0, 5, 5, 5, 5, 4, 0, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5, 4,
       0, 5, 5, 1, 0, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 5,
       1, 0, 5, 5, 5, 4, 0, 5, 4, 0, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 4, 0, 1, 0, 1, 0, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0,
       5, 5, 5, 5, 5, 5, 5, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 5, 5,
       5, 5, 5, 4, 0, 5, 4, 0, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 1, 0, 5, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4,
       0, 5, 5, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       1, 0, 5, 5, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 5, 5, 1, 0, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 0, 5, 1, 0, 5, 5, 5, 5, 5, 4, 0, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 4], dtype=int64)

In [20]:
system.single_state_lifetimes

{'single_state_occurrences': [array([0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.]),
  array([0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
         1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.])],
 'single_state_occurrences_all': array([0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.]),
 'single_state_occurrences_pred': None,
 'lifetimes_fluorophore': [array([1.28818253e-08, 1.03414550e-10, 1.90706206e-09, 1.96027040e-11,
         3.11244153e-11, 1.55685219e-12, 3.85734364e-11, 4.25526187e-11,
         3.52418170e-13, 2.16553651e-11, 1.93888659e-13, 7.76566709e-11,
         1.23493053e-11, 3.07288847e-11, 3.37009597e-08, 3.51560602e-10,
         2.18651042e-10, 5.03105047e-11, 3.74917992e-12, 5.69433996e-11,
         3.49885807e-11, 1.94917848e-10, 4.40012227e-11, 4.29376131e-11,
         4.14094045e-08, 4.52219236e-11, 8.03631543e-08, 6.35333691e-11,
         5.84013963e-08, 2.89179855e-11, 8.58160159e-11, 5.60382377e-11,
         9.22432423e-11, 3.42516695e-11, 4.60617572e-11, 2.06992919e-11,
         1.06513161e-10, 2.62196790e-11, 1.40699656e-10, 2.28159315e-11,
         4.63577060e-13, 1.80024989e-11, 2.28485178e-12, 1.24981036e-11,
         1.03590738e-10, 1.04806808e-10, 2.34598494e-10, 2.68424366e-10,
         8.22435392e-09, 7.88610559e-12, 3.49189186e-11, 1.06700709e-11,
         1.08890508e-10, 6.14677684e-13, 4.07405711e-11, 3.14022869e-11,
         9.77185142e-11, 9.59798727e-11, 2.81446225e-10, 7.53669305e-11,
         4.70260084e-11, 9.53182181e-12, 3.59950970e-12, 8.79790916e-11,
         3.98559050e-11, 1.85507294e-10, 1.40100943e-10, 9.67654051e-12,
         2.56332982e-10, 1.24652105e-11, 7.25437653e-11, 2.36324721e-12,
         4.85532604e-11, 1.33475663e-11, 6.97261688e-12, 9.31314405e-11,
         2.44232350e-11, 2.06516002e-10, 1.98579101e-10, 1.86210630e-11,
         4.72184329e-08, 4.55474732e-12, 7.80467718e-11, 1.66181125e-11,
         1.76955797e-11, 1.64829623e-10, 2.00428807e-10, 2.86868024e-11,
         8.57675337e-11, 6.89951985e-11, 4.07902092e-11, 1.26931118e-10,
         1.41228712e-10, 1.04016212e-10, 3.06644081e-11, 5.94361377e-11,
         1.83209926e-08, 3.43970265e-11, 1.23028618e-07, 2.95980617e-11,
         1.24256868e-10, 2.07332653e-10, 1.96897028e-11, 4.40080096e-11,
         9.55631688e-08, 6.86139262e-11, 4.43948389e-08, 1.41620011e-10,
         2.97665341e-11, 1.91240396e-11, 6.65253326e-11, 3.67678176e-11,
         1.48045529e-10, 2.61628559e-11, 1.03592634e-10, 3.11648975e-11,
         8.01049225e-09, 1.27161050e-10, 2.16261997e-11, 6.49698424e-11,
         2.48971335e-12, 1.73989278e-10, 1.63946970e-11, 6.39111854e-11,
         4.03149801e-12, 2.57200283e-10, 5.71450386e-08, 4.07928552e-11,
         1.00813450e-08, 8.53838288e-11, 1.88176499e-11, 2.07028044e-11,
         2.48062932e-08, 4.55773404e-11, 1.60682060e-08, 1.36222062e-12,
         3.75915258e-11, 5.58826542e-11, 2.32970212e-11, 5.18980947e-11,
         1.56533792e-08, 1.46860317e-10, 6.79178153e-11, 3.45024952e-11,
         1.58788206e-10, 2.14593526e-11, 3.72473597e-08, 2.81147200e-11,
         3.29518424e-12, 1.67239111e-10, 3.07882993e-11, 2.97372598e-11,
         1.18826279e-11, 7.69156107e-11, 7.08968427e-11, 5.93532317e-11,
         1.58508824e-10, 5.41082867e-11, 1.35974334e-11, 5.38567098e-11,
         1.54530740e-10, 1.45604112e-11, 2.04013572e-10, 1.11059141e-10,
         9.95955613e-09, 2.32458894e-10, 2.67876725e-11, 3.75047246e-12,
         8.91179402e-11, 1.20275115e-11, 2.17158159e-11, 9.66596747e-11,
         3.81762436e-08, 1.78825815e-10, 2.62149773e-11, 1.56131205e-11,
         8.26165123e-11, 3.10374866e-11, 1.51218688e-11, 1.23067679e-10,
         5.31867634e-08, 1.81208923e-12, 2.35040862e-07, 6.64732017e-11,
         1.03313815e-11, 2.44759815e-11, 4.83162437e-11, 5.77338898e-12,
         4.26858645e-11, 3.21027658e-11, 1.05617546e-10, 5.63762915e-11,
         8.20667163e-08, 3.26551518e-10, 2.21269238e-10, 1.52030737e-10,
         5.04195850e-11, 7.50527981e-11, 1.03089147e-10, 2.66357027e-11,
         1.50063508e-12, 3.47249499e-12, 7.86308953e-11, 7.86976421e-11,
         2.87309331e-10, 1.17186298e-10, 1.92222413e-12, 1.31790158e-10,
         7.96031279e-11, 1.66070140e-10, 1.34746822e-10, 2.45876335e-10,
         1.68869103e-10, 6.35063158e-11, 4.51984880e-11, 5.65798166e-11,
         1.33401241e-11, 1.98318563e-11, 6.26399791e-11, 2.48409470e-11,
         1.15454278e-08, 7.24187623e-11, 1.11238309e-10, 8.31206543e-11,
         1.39785043e-08, 1.60703972e-10, 2.54147730e-10, 8.28378817e-12,
         3.52362820e-11, 1.38399130e-11, 4.13833020e-08, 1.48576268e-11,
         6.60312627e-11, 1.18510006e-10, 3.17450129e-08, 2.36724736e-10,
         9.21628093e-08, 4.60425143e-11, 1.41615643e-07, 1.88549852e-11,
         1.01054356e-10, 2.30049978e-10, 2.57339078e-11, 9.34024367e-12,
         2.79410897e-10, 9.71070644e-11, 6.73944106e-12, 1.24122050e-10,
         1.84787899e-12, 2.33813334e-10, 1.52695377e-07, 3.52441857e-11,
         4.95075393e-08, 1.27456692e-11, 9.09197171e-11, 1.56825090e-11,
         3.37605141e-08, 6.56123075e-11, 2.13102936e-07, 1.92638329e-10,
         1.08699442e-10, 8.33708900e-11, 1.24265734e-11, 1.41423446e-10,
         2.85617957e-11, 1.19565297e-10, 5.06742820e-11, 9.59515099e-11,
         3.67916018e-11, 1.08343065e-10, 1.12353297e-10, 3.36294409e-11,
         1.03131537e-10, 1.62789055e-11, 1.39794223e-07, 2.59111791e-10,
         1.34811192e-07, 1.48790119e-11, 1.70247153e-11, 8.30577182e-11,
         1.07959215e-10, 7.43400934e-12, 5.14936813e-08, 9.29301527e-11,
         6.90770148e-11, 6.50049403e-12, 3.24958031e-12, 1.72244115e-11,
         1.20347507e-10, 8.90049243e-11, 4.99017071e-12, 1.30194963e-11,
         1.24438210e-10, 3.18931913e-11, 5.93378110e-11, 1.68032058e-11,
         3.80372603e-08, 1.74224452e-11, 5.91226351e-11, 1.74768010e-11,
         1.54527527e-10, 1.13755686e-11, 4.72284721e-11, 2.90561765e-12,
         4.12486629e-11, 6.22380478e-11, 1.21628013e-07, 4.29883379e-11,
         1.56961870e-10, 4.64875827e-11, 1.22028452e-10, 1.54645416e-10,
         3.89300477e-11, 3.57633080e-11, 4.79316168e-08, 3.02777847e-11,
         6.62726478e-11, 2.51543703e-11, 5.25651370e-11, 3.14879854e-12,
         2.00343115e-10, 2.58178709e-11, 1.08971588e-10, 5.75233229e-11,
         1.22003300e-08, 4.58856623e-11, 7.14325705e-11, 5.15774509e-11,
         5.37444394e-11, 2.47884702e-10, 2.03084266e-08, 4.97561014e-11,
         1.67720245e-08, 2.83697244e-11, 1.42605172e-09, 1.27276540e-10,
         1.04384683e-10, 1.04258864e-11, 8.80507759e-12, 4.96043218e-11,
         9.75804697e-13, 1.42321659e-11, 8.81454529e-11, 1.07475761e-10,
         1.82950161e-11, 2.30462882e-11, 1.77305540e-11, 1.05645987e-11,
         1.64546867e-11, 3.32139825e-12, 3.95201631e-09, 8.60337492e-11,
         2.78277074e-08, 2.67444870e-11, 1.07904578e-10, 5.75317874e-12,
         1.98626765e-11, 4.21527529e-11, 3.40033158e-11, 7.02387853e-11,
         5.84081886e-11, 5.63095660e-11, 4.34681386e-12, 1.09278690e-10,
         9.59536255e-11, 2.98100227e-11, 1.96059367e-07, 2.04812307e-10,
         7.82681964e-12, 2.90557655e-10, 1.54797110e-08, 1.75817359e-11,
         6.85701731e-12, 5.17938179e-12, 2.43768015e-11, 4.60697715e-11,
         7.77629230e-11, 5.47757131e-11, 1.10065026e-10, 3.79640042e-12,
         8.52310235e-11, 1.19429962e-12, 1.42364285e-11, 6.35941690e-11,
         1.57521864e-11, 9.79376450e-11, 9.27050014e-12, 8.38787673e-11,
         5.78220676e-10, 1.23240605e-10, 8.35869890e-11, 4.35383412e-12,
         1.39753223e-07, 1.52090687e-12, 1.00907690e-10, 1.54729308e-10,
         2.84389418e-11, 1.65865945e-10, 5.19129283e-11, 1.58336726e-10,
         1.16313312e-10, 2.08651292e-13, 1.09238442e-07, 1.41246842e-10,
         3.55543697e-07, 2.00473718e-10, 1.90326444e-11, 1.57648412e-10,
         4.92598328e-11, 4.90869700e-11, 1.03465641e-10, 1.15299782e-10,
         2.11309855e-11, 5.77844889e-11, 5.46721398e-08, 1.03854679e-10,
         1.34010702e-08, 2.89826701e-11, 8.78213317e-11, 8.36747123e-11,
         5.02387617e-11, 9.54465676e-11, 7.82004399e-08, 4.49451834e-12,
         1.39698652e-10, 9.99986069e-11, 2.17791835e-11, 6.31861505e-11,
         7.23743356e-11, 5.18238866e-11, 9.49569193e-11, 8.90494573e-11,
         5.01070183e-11, 2.89111533e-10, 2.23955008e-12, 5.51946209e-11,
         1.67211114e-10, 4.94161623e-11, 8.35926362e-08, 2.95494043e-10]),
  array([1.49119046e-08, 3.11244153e-11, 1.55685219e-12, 3.85734364e-11,
         4.25526187e-11, 3.52418170e-13, 2.16553651e-11, 1.93888659e-13,
         7.76566709e-11, 1.23493053e-11, 3.07288847e-11, 7.84652686e-11,
         3.35148547e-08, 1.07639753e-10, 3.51560602e-10, 2.18651042e-10,
         5.03105047e-11, 3.74917992e-12, 5.69433996e-11, 3.49885807e-11,
         1.94917848e-10, 4.40012227e-11, 4.14975640e-08, 2.85665554e-11,
         8.03104110e-08, 2.41767106e-11, 5.83654874e-08, 9.94422541e-11,
         2.89179855e-11, 8.58160159e-11, 5.60382377e-11, 9.22432423e-11,
         3.42516695e-11, 4.60617572e-11, 2.06992919e-11, 1.06513161e-10,
         2.62196790e-11, 1.40699656e-10, 2.28159315e-11, 4.63577060e-13,
         1.80024989e-11, 2.28485178e-12, 1.24981036e-11, 1.03590738e-10,
         1.04806808e-10, 5.29627631e-10, 8.20563525e-09, 3.49189186e-11,
         1.06700709e-11, 1.08890508e-10, 6.14677684e-13, 4.07405711e-11,
         3.14022869e-11, 9.77185142e-11, 9.59798727e-11, 2.81446225e-10,
         7.53669305e-11, 4.70260084e-11, 9.53182181e-12, 3.59950970e-12,
         8.79790916e-11, 3.98559050e-11, 1.85507294e-10, 1.40100943e-10,
         9.67654051e-12, 2.56332982e-10, 1.24652105e-11, 7.25437653e-11,
         2.36324721e-12, 4.85532604e-11, 1.33475663e-11, 6.97261688e-12,
         9.31314405e-11, 2.44232350e-11, 2.06516002e-10, 1.98579101e-10,
         1.86210630e-11, 1.07252456e-10, 4.71157352e-08, 7.80467718e-11,
         1.66181125e-11, 1.76955797e-11, 1.64829623e-10, 2.00428807e-10,
         2.86868024e-11, 8.57675337e-11, 6.89951985e-11, 4.07902092e-11,
         1.26931118e-10, 1.41228712e-10, 1.04016212e-10, 3.06644081e-11,
         1.83309673e-08, 4.94614138e-11, 1.23092613e-07, 1.24256868e-10,
         2.07332653e-10, 1.96897028e-11, 4.40080096e-11, 8.81801746e-11,
         3.13042131e-08, 2.13075483e-11, 1.08274049e-07, 3.38871636e-10,
         1.41620011e-10, 2.97665341e-11, 1.91240396e-11, 6.65253326e-11,
         3.67678176e-11, 1.48045529e-10, 2.61628559e-11, 1.03592634e-10,
         3.11648975e-11, 1.88741587e-11, 8.11877914e-09, 2.16261997e-11,
         6.49698424e-11, 2.48971335e-12, 1.73989278e-10, 1.63946970e-11,
         6.39111854e-11, 4.03149801e-12, 5.74430317e-08, 1.42449202e-10,
         1.00242796e-08, 1.88176499e-11, 2.07028044e-11, 7.33249272e-11,
         2.46022352e-08, 1.30733072e-10, 1.60142282e-08, 9.95551705e-11,
         1.36222062e-12, 3.75915258e-11, 5.58826542e-11, 2.32970212e-11,
         1.56364580e-08, 6.88192511e-11, 1.46860317e-10, 6.79178153e-11,
         3.45024952e-11, 1.58788206e-10, 2.14593526e-11, 1.70491329e-10,
         3.71049831e-08, 3.29518424e-12, 1.67239111e-10, 3.07882993e-11,
         2.97372598e-11, 1.18826279e-11, 7.69156107e-11, 7.08968427e-11,
         5.93532317e-11, 1.58508824e-10, 5.41082867e-11, 1.35974334e-11,
         5.38567098e-11, 1.54530740e-10, 1.45604112e-11, 2.04013572e-10,
         1.11059141e-10, 1.27221707e-10, 1.00647933e-08, 2.67876725e-11,
         3.75047246e-12, 8.91179402e-11, 1.20275115e-11, 2.17158159e-11,
         3.84517291e-08, 2.62149773e-11, 1.56131205e-11, 8.26165123e-11,
         3.10374866e-11, 1.51218688e-11, 1.23067679e-10, 2.38831770e-10,
         1.35692711e-07, 8.30205988e-11, 1.52060726e-07, 1.54148267e-10,
         6.64732017e-11, 1.03313815e-11, 2.44759815e-11, 4.83162437e-11,
         5.77338898e-12, 4.26858645e-11, 3.21027658e-11, 1.05617546e-10,
         8.20878373e-08, 3.52552593e-11, 3.26551518e-10, 2.21269238e-10,
         1.52030737e-10, 5.04195850e-11, 7.50527981e-11, 1.03089147e-10,
         2.66357027e-11, 1.50063508e-12, 3.47249499e-12, 7.86308953e-11,
         7.86976421e-11, 4.36842915e-11, 3.60811337e-10, 1.92222413e-12,
         1.31790158e-10, 7.96031279e-11, 1.66070140e-10, 1.34746822e-10,
         2.45876335e-10, 1.68869103e-10, 6.35063158e-11, 4.51984880e-11,

In [21]:
system.transition_lifetimes

{'transition_occurrences': [array([0, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
         5, 4, 0, 5, 5, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
         5, 5, 0, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 5, 1, 5, 1, 0, 5, 5, 5, 5, 5, 0, 1, 5, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 5, 0, 5, 5, 5,
         5, 4, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5,
         5, 5, 5, 5, 0, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4,
         5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 4, 5, 5, 0, 4, 5, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 0, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 1, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 1, 5, 5,
         5, 5, 5, 5, 5, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4,
         5, 4, 0, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1,
         0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 5, 4, 0, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 5, 1, 0, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 5, 5,
         5, 5, 5, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 4],
        dtype=int64),
  array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5,
         5, 1, 0, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
         5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
         5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 4, 0, 4, 0, 5, 5, 5, 5, 5, 5, 5,
         5, 5, 5, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 5, 5, 5, 4, 0, 5, 0, 5,
         5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1,
         0, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5,
         5, 5, 5, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5,
         5, 4, 0, 5, 5, 5, 5, 5, 0, 5, 5, 5, 0, 5, 5, 1, 0, 5, 5, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 5, 1, 5, 1, 5, 5, 5, 4, 0, 5, 0, 1, 0, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 0, 1, 0, 5, 5, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5,
         0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 5, 5, 5,
         5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 5,
         5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
         5, 1, 0, 5, 5, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 0, 5, 0, 5,
         5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int64)],
 'transition_occurrences_all': array([0, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 4, 0, 5, 1, 0, 5, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 0, 4, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 5, 1, 0, 5, 5, 5,
        5, 5, 4, 0, 4, 0, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 5, 5,
        5, 5, 5, 5, 5, 5, 1, 0, 5, 1, 0, 5, 5, 5, 4, 0, 5, 4, 0, 5, 5, 5,
        5, 5, 4, 0, 5, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5, 5, 5,
        5, 5, 1, 0, 4, 0, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 4, 0, 5, 5, 5, 5, 4, 0, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5, 4,
        0, 5, 5, 1, 0, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 5,
        1, 0, 5, 5, 5, 4, 0, 5, 4, 0, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 4, 0, 1, 0, 1, 0, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0,
        5, 5, 5, 5, 5, 5, 5, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 5, 5,
        5, 5, 5, 4, 0, 5, 4, 0, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 1, 0, 5, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4,
        0, 5, 5, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        1, 0, 5, 5, 1, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 5, 5, 1, 0, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 0, 5, 1, 0, 5, 5, 5, 5, 5, 4, 0, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 0, 4], dtype=int64),
 'transition_occurrences_pred': None,
 'transition_times': [[array([1.28818253e-08, 1.90706206e-09, 4.14094045e-08, 2.34598494e-10,
          8.22435392e-09, 4.72184329e-08, 1.23028618e-07, 9.55631688e-08,
          8.01049225e-09, 5.71450386e-08, 1.00813450e-08, 3.72473597e-08,
          9.95955613e-09, 3.81762436e-08, 5.31867634e-08, 2.87309331e-10,
          9.21628093e-08, 1.52695377e-07, 4.95075393e-08, 1.39794223e-07,
          5.14936813e-08, 3.80372603e-08, 4.79316168e-08, 1.67720245e-08,
          1.42605172e-09, 2.78277074e-08, 1.96059367e-07, 1.54797110e-08,
          5.78220676e-10, 1.39753223e-07, 7.82004399e-08, 8.35926362e-08]),
   array([6.35333691e-11, 5.94361377e-11, 3.43970265e-11, 6.86139262e-11,
          2.57200283e-10, 2.59111791e-10, 6.22380478e-11, 3.57633080e-11,
          2.83697244e-11, 8.60337492e-11, 4.35383412e-12, 1.03854679e-10,
          4.94161623e-11]),
   array([], dtype=float64),
   array([], dtype=float64),
   array([1.03414550e-10, 4.29376131e-11, 2.68424366e-10, 4.55773404e-11,
          5.18980947e-11, 9.66596747e-11, 1.81208923e-12, 5.63762915e-11,
          2.48409470e-11, 1.38399130e-11, 1.18510006e-10, 4.60425143e-11,
          6.56123075e-11, 7.43400934e-12, 2.47884702e-10, 4.97561014e-11,
          2.90557655e-10, 9.54465676e-11, 2.95494043e-10]),
   array([1.96027040e-11, 3.11244153e-11, 1.55685219e-12, 3.85734364e-11,
          4.25526187e-11, 3.52418170e-13, 2.16553651e-11, 1.93888659e-13,
          7.76566709e-11, 1.23493053e-11, 3.07288847e-11, 3.37009597e-08,
          3.51560602e-10, 2.18651042e-10, 5.03105047e-11, 3.74917992e-12,
          5.69433996e-11, 3.49885807e-11, 1.94917848e-10, 4.40012227e-11,
          4.52219236e-11, 8.03631543e-08, 5.84013963e-08, 2.89179855e-11,
          8.58160159e-11, 5.60382377e-11, 9.22432423e-11, 3.42516695e-11,
          4.60617572e-11, 2.06992919e-11, 1.06513161e-10, 2.62196790e-11,
          1.40699656e-10, 2.28159315e-11, 4.63577060e-13, 1.80024989e-11,
          2.28485178e-12, 1.24981036e-11, 1.03590738e-10, 1.04806808e-10,
          7.88610559e-12, 3.49189186e-11, 1.06700709e-11, 1.08890508e-10,
          6.14677684e-13, 4.07405711e-11, 3.14022869e-11, 9.77185142e-11,
          9.59798727e-11, 2.81446225e-10, 7.53669305e-11, 4.70260084e-11,
          9.53182181e-12, 3.59950970e-12, 8.79790916e-11, 3.98559050e-11,
          1.85507294e-10, 1.40100943e-10, 9.67654051e-12, 2.56332982e-10,
          1.24652105e-11, 7.25437653e-11, 2.36324721e-12, 4.85532604e-11,
          1.33475663e-11, 6.97261688e-12, 9.31314405e-11, 2.44232350e-11,
          2.06516002e-10, 1.98579101e-10, 1.86210630e-11, 4.55474732e-12,
          7.80467718e-11, 1.66181125e-11, 1.76955797e-11, 1.64829623e-10,
          2.00428807e-10, 2.86868024e-11, 8.57675337e-11, 6.89951985e-11,
          4.07902092e-11, 1.26931118e-10, 1.41228712e-10, 1.04016212e-10,
          3.06644081e-11, 1.83209926e-08, 2.95980617e-11, 1.24256868e-10,
          2.07332653e-10, 1.96897028e-11, 4.40080096e-11, 4.43948389e-08,
          1.41620011e-10, 2.97665341e-11, 1.91240396e-11, 6.65253326e-11,
          3.67678176e-11, 1.48045529e-10, 2.61628559e-11, 1.03592634e-10,
          3.11648975e-11, 1.27161050e-10, 2.16261997e-11, 6.49698424e-11,
          2.48971335e-12, 1.73989278e-10, 1.63946970e-11, 6.39111854e-11,
          4.03149801e-12, 4.07928552e-11, 8.53838288e-11, 1.88176499e-11,
          2.07028044e-11, 2.48062932e-08, 1.60682060e-08, 1.36222062e-12,
          3.75915258e-11, 5.58826542e-11, 2.32970212e-11, 1.56533792e-08,
          1.46860317e-10, 6.79178153e-11, 3.45024952e-11, 1.58788206e-10,
          2.14593526e-11, 2.81147200e-11, 3.29518424e-12, 1.67239111e-10,
          3.07882993e-11, 2.97372598e-11, 1.18826279e-11, 7.69156107e-11,
          7.08968427e-11, 5.93532317e-11, 1.58508824e-10, 5.41082867e-11,
          1.35974334e-11, 5.38567098e-11, 1.54530740e-10, 1.45604112e-11,
          2.04013572e-10, 1.11059141e-10, 2.32458894e-10, 2.67876725e-11,
          3.75047246e-12, 8.91179402e-11, 1.20275115e-11, 2.17158159e-11,
          1.78825815e-10, 2.62149773e-11, 1.56131205e-11, 8.26165123e-11,
          3.10374866e-11, 1.51218688e-11, 1.23067679e-10, 2.35040862e-07,
          6.64732017e-11, 1.03313815e-11, 2.44759815e-11, 4.83162437e-11,
          5.77338898e-12, 4.26858645e-11, 3.21027658e-11, 1.05617546e-10,
          8.20667163e-08, 3.26551518e-10, 2.21269238e-10, 1.52030737e-10,
          5.04195850e-11, 7.50527981e-11, 1.03089147e-10, 2.66357027e-11,
          1.50063508e-12, 3.47249499e-12, 7.86308953e-11, 7.86976421e-11,
          1.17186298e-10, 1.92222413e-12, 1.31790158e-10, 7.96031279e-11,
          1.66070140e-10, 1.34746822e-10, 2.45876335e-10, 1.68869103e-10,
          6.35063158e-11, 4.51984880e-11, 5.65798166e-11, 1.33401241e-11,
          1.98318563e-11, 6.26399791e-11, 1.15454278e-08, 7.24187623e-11,
          1.11238309e-10, 8.31206543e-11, 1.39785043e-08, 1.60703972e-10,
          2.54147730e-10, 8.28378817e-12, 3.52362820e-11, 4.13833020e-08,
          1.48576268e-11, 6.60312627e-11, 3.17450129e-08, 2.36724736e-10,
          1.41615643e-07, 1.88549852e-11, 1.01054356e-10, 2.30049978e-10,
          2.57339078e-11, 9.34024367e-12, 2.79410897e-10, 9.71070644e-11,
          6.73944106e-12, 1.24122050e-10, 1.84787899e-12, 2.33813334e-10,
          3.52441857e-11, 1.27456692e-11, 9.09197171e-11, 1.56825090e-11,
          3.37605141e-08, 2.13102936e-07, 1.92638329e-10, 1.08699442e-10,
          8.33708900e-11, 1.24265734e-11, 1.41423446e-10, 2.85617957e-11,
          1.19565297e-10, 5.06742820e-11, 9.59515099e-11, 3.67916018e-11,
          1.08343065e-10, 1.12353297e-10, 3.36294409e-11, 1.03131537e-10,
          1.62789055e-11, 1.34811192e-07, 1.48790119e-11, 1.70247153e-11,
          8.30577182e-11, 1.07959215e-10, 9.29301527e-11, 6.90770148e-11,
          6.50049403e-12, 3.24958031e-12, 1.72244115e-11, 1.20347507e-10,
          8.90049243e-11, 4.99017071e-12, 1.30194963e-11, 1.24438210e-10,
          3.18931913e-11, 5.93378110e-11, 1.68032058e-11, 1.74224452e-11,
          5.91226351e-11, 1.74768010e-11, 1.54527527e-10, 1.13755686e-11,
          4.72284721e-11, 2.90561765e-12, 4.12486629e-11, 1.21628013e-07,
          4.29883379e-11, 1.56961870e-10, 4.64875827e-11, 1.22028452e-10,
          1.54645416e-10, 3.89300477e-11, 3.02777847e-11, 6.62726478e-11,
          2.51543703e-11, 5.25651370e-11, 3.14879854e-12, 2.00343115e-10,
          2.58178709e-11, 1.08971588e-10, 5.75233229e-11, 1.22003300e-08,
          4.58856623e-11, 7.14325705e-11, 5.15774509e-11, 5.37444394e-11,
          2.03084266e-08, 1.27276540e-10, 1.04384683e-10, 1.04258864e-11,
          8.80507759e-12, 4.96043218e-11, 9.75804697e-13, 1.42321659e-11,
          8.81454529e-11, 1.07475761e-10, 1.82950161e-11, 2.30462882e-11,
          1.77305540e-11, 1.05645987e-11, 1.64546867e-11, 3.32139825e-12,
          3.95201631e-09, 2.67444870e-11, 1.07904578e-10, 5.75317874e-12,
          1.98626765e-11, 4.21527529e-11, 3.40033158e-11, 7.02387853e-11,
          5.84081886e-11, 5.63095660e-11, 4.34681386e-12, 1.09278690e-10,
          9.59536255e-11, 2.98100227e-11, 2.04812307e-10, 7.82681964e-12,
          1.75817359e-11, 6.85701731e-12, 5.17938179e-12, 2.43768015e-11,
          4.60697715e-11, 7.77629230e-11, 5.47757131e-11, 1.10065026e-10,
          3.79640042e-12, 8.52310235e-11, 1.19429962e-12, 1.42364285e-11,
          6.35941690e-11, 1.57521864e-11, 9.79376450e-11, 9.27050014e-12,
          8.38787673e-11, 1.23240605e-10, 8.35869890e-11, 1.52090687e-12,
          1.00907690e-10, 1.54729308e-10, 2.84389418e-11, 1.65865945e-10,
          5.19129283e-11, 1.58336726e-10, 1.16313312e-10, 2.08651292e-13,
          1.09238442e-07, 1.41246842e-10, 3.55543697e-07, 2.00473718e-10,
          1.90326444e-11, 1.57648412e-10, 4.92598328e-11, 4.90869700e-11,
          1.03465641e-10, 1.15299782e-10, 2.11309855e-11, 5.77844889e-11,
          5.46721398e-08, 1.34010702e-08, 2.89826701e-11, 8.78213317e-11,
          8.36747123e-11, 5.02387617e-11, 4.49451834e-12, 1.39698652e-10,
          9.99986069e-11, 2.17791835e-11, 6.31861505e-11, 7.23743356e-11,
          5.18238866e-11, 9.49569193e-11, 8.90494573e-11, 5.01070183e-11,
          2.89111533e-10, 2.23955008e-12, 5.51946209e-11, 1.67211114e-10])],
  [array([3.35148547e-08, 8.03104110e-08, 5.83654874e-08, 1.83309673e-08,
          3.13042131e-08, 1.08274049e-07, 2.46022352e-08, 1.60142282e-08,
          1.56364580e-08, 1.35692711e-07, 1.52060726e-07, 8.20878373e-08,
          1.15605078e-08, 1.38646559e-08, 4.13066092e-08, 3.18163012e-08,
          2.33563183e-07, 3.35385751e-08, 1.15642398e-07, 9.72741547e-08,
          1.52602384e-07, 1.22052647e-07, 1.21617520e-07, 1.19507430e-08,
          2.05202186e-08, 3.82164437e-09, 1.08789980e-07, 3.55494882e-07,
          5.44800146e-08, 1.34337246e-08]),
   array([2.85665554e-11, 1.07252456e-10, 1.88741587e-11, 1.42449202e-10,
          2.38831770e-10, 8.30205988e-11, 4.36842915e-11, 8.21069148e-11,
          6.73799890e-12, 4.39188551e-11, 4.05445093e-11, 6.66113921e-11,
          9.01336109e-11, 5.69090948e-11, 8.07024053e-11, 1.64758983e-10,
          3.61320341e-11]),
   array([], dtype=float64),
   array([], dtype=float64),
   array([7.84652686e-11, 5.29627631e-10, 8.81801746e-11, 2.13075483e-11,
          7.33249272e-11, 1.70491329e-10, 1.27221707e-10, 8.66369140e-11,
          9.06863078e-11, 1.26713971e-10, 1.13760625e-10, 6.12784601e-13,
          4.11526687e-11]),
   array([1.49119046e-08, 3.11244153e-11, 1.55685219e-12, 3.85734364e-11,
          4.25526187e-11, 3.52418170e-13, 2.16553651e-11, 1.93888659e-13,
          7.76566709e-11, 1.23493053e-11, 3.07288847e-11, 1.07639753e-10,
          3.51560602e-10, 2.18651042e-10, 5.03105047e-11, 3.74917992e-12,
          5.69433996e-11, 3.49885807e-11, 1.94917848e-10, 4.40012227e-11,
          4.14975640e-08, 2.41767106e-11, 9.94422541e-11, 2.89179855e-11,
          8.58160159e-11, 5.60382377e-11, 9.22432423e-11, 3.42516695e-11,
          4.60617572e-11, 2.06992919e-11, 1.06513161e-10, 2.62196790e-11,
          1.40699656e-10, 2.28159315e-11, 4.63577060e-13, 1.80024989e-11,
          2.28485178e-12, 1.24981036e-11, 1.03590738e-10, 1.04806808e-10,
          8.20563525e-09, 3.49189186e-11, 1.06700709e-11, 1.08890508e-10,
          6.14677684e-13, 4.07405711e-11, 3.14022869e-11, 9.77185142e-11,
          9.59798727e-11, 2.81446225e-10, 7.53669305e-11, 4.70260084e-11,
          9.53182181e-12, 3.59950970e-12, 8.79790916e-11, 3.98559050e-11,
          1.85507294e-10, 1.40100943e-10, 9.67654051e-12, 2.56332982e-10,
          1.24652105e-11, 7.25437653e-11, 2.36324721e-12, 4.85532604e-11,
          1.33475663e-11, 6.97261688e-12, 9.31314405e-11, 2.44232350e-11,
          2.06516002e-10, 1.98579101e-10, 1.86210630e-11, 4.71157352e-08,
          7.80467718e-11, 1.66181125e-11, 1.76955797e-11, 1.64829623e-10,
          2.00428807e-10, 2.86868024e-11, 8.57675337e-11, 6.89951985e-11,
          4.07902092e-11, 1.26931118e-10, 1.41228712e-10, 1.04016212e-10,
          3.06644081e-11, 4.94614138e-11, 1.23092613e-07, 1.24256868e-10,
          2.07332653e-10, 1.96897028e-11, 4.40080096e-11, 3.38871636e-10,
          1.41620011e-10, 2.97665341e-11, 1.91240396e-11, 6.65253326e-11,
          3.67678176e-11, 1.48045529e-10, 2.61628559e-11, 1.03592634e-10,
          3.11648975e-11, 8.11877914e-09, 2.16261997e-11, 6.49698424e-11,
          2.48971335e-12, 1.73989278e-10, 1.63946970e-11, 6.39111854e-11,
          4.03149801e-12, 5.74430317e-08, 1.00242796e-08, 1.88176499e-11,
          2.07028044e-11, 1.30733072e-10, 9.95551705e-11, 1.36222062e-12,
          3.75915258e-11, 5.58826542e-11, 2.32970212e-11, 6.88192511e-11,
          1.46860317e-10, 6.79178153e-11, 3.45024952e-11, 1.58788206e-10,
          2.14593526e-11, 3.71049831e-08, 3.29518424e-12, 1.67239111e-10,
          3.07882993e-11, 2.97372598e-11, 1.18826279e-11, 7.69156107e-11,
          7.08968427e-11, 5.93532317e-11, 1.58508824e-10, 5.41082867e-11,
          1.35974334e-11, 5.38567098e-11, 1.54530740e-10, 1.45604112e-11,
          2.04013572e-10, 1.11059141e-10, 1.00647933e-08, 2.67876725e-11,
          3.75047246e-12, 8.91179402e-11, 1.20275115e-11, 2.17158159e-11,
          3.84517291e-08, 2.62149773e-11, 1.56131205e-11, 8.26165123e-11,
          3.10374866e-11, 1.51218688e-11, 1.23067679e-10, 1.54148267e-10,
          6.64732017e-11, 1.03313815e-11, 2.44759815e-11, 4.83162437e-11,
          5.77338898e-12, 4.26858645e-11, 3.21027658e-11, 1.05617546e-10,
          3.52552593e-11, 3.26551518e-10, 2.21269238e-10, 1.52030737e-10,
          5.04195850e-11, 7.50527981e-11, 1.03089147e-10, 2.66357027e-11,
          1.50063508e-12, 3.47249499e-12, 7.86308953e-11, 7.86976421e-11,
          3.60811337e-10, 1.92222413e-12, 1.31790158e-10, 7.96031279e-11,
          1.66070140e-10, 1.34746822e-10, 2.45876335e-10, 1.68869103e-10,
          6.35063158e-11, 4.51984880e-11, 5.65798166e-11, 1.33401241e-11,
          1.98318563e-11, 6.26399791e-11, 9.76097720e-12, 7.24187623e-11,
          1.11238309e-10, 8.31206543e-11, 2.72114487e-11, 1.60703972e-10,
          2.54147730e-10, 8.28378817e-12, 3.52362820e-11, 9.05326446e-11,
          1.48576268e-11, 6.60312627e-11, 4.72217152e-11, 2.36724736e-10,
          1.79204368e-10, 1.88549852e-11, 1.01054356e-10, 2.30049978e-10,
          2.57339078e-11, 9.34024367e-12, 2.79410897e-10, 9.71070644e-11,
          6.73944106e-12, 1.24122050e-10, 1.84787899e-12, 2.33813334e-10,
          1.52723883e-07, 4.94763661e-08, 9.09197171e-11, 1.56825090e-11,
          1.31252700e-10, 2.11451629e-10, 1.92638329e-10, 1.08699442e-10,
          8.33708900e-11, 1.24265734e-11, 1.41423446e-10, 2.85617957e-11,
          1.19565297e-10, 5.06742820e-11, 9.59515099e-11, 3.67916018e-11,
          1.08343065e-10, 1.12353297e-10, 3.36294409e-11, 1.03131537e-10,
          1.62789055e-11, 1.61694631e-11, 1.48790119e-11, 1.70247153e-11,
          8.30577182e-11, 1.07959215e-10, 5.15940455e-08, 6.90770148e-11,
          6.50049403e-12, 3.24958031e-12, 1.72244115e-11, 1.20347507e-10,
          8.90049243e-11, 4.99017071e-12, 1.30194963e-11, 1.24438210e-10,
          3.18931913e-11, 5.93378110e-11, 1.68032058e-11, 3.79409221e-08,
          5.91226351e-11, 1.74768010e-11, 1.54527527e-10, 1.13755686e-11,
          4.72284721e-11, 2.90561765e-12, 4.12486629e-11, 7.27306383e-11,
          4.29883379e-11, 1.56961870e-10, 4.64875827e-11, 1.22028452e-10,
          1.54645416e-10, 3.89300477e-11, 4.79976579e-08, 6.62726478e-11,
          2.51543703e-11, 5.25651370e-11, 3.14879854e-12, 2.00343115e-10,
          2.58178709e-11, 1.08971588e-10, 5.75233229e-11, 1.59453373e-10,
          4.58856623e-11, 7.14325705e-11, 5.15774509e-11, 5.37444394e-11,
          3.60927589e-11, 1.84034786e-08, 1.04384683e-10, 1.04258864e-11,
          8.80507759e-12, 4.96043218e-11, 9.75804697e-13, 1.42321659e-11,
          8.81454529e-11, 1.07475761e-10, 1.82950161e-11, 2.30462882e-11,
          1.77305540e-11, 1.05645987e-11, 1.64546867e-11, 3.32139825e-12,
          7.34628505e-11, 2.79404856e-08, 1.07904578e-10, 5.75317874e-12,
          1.98626765e-11, 4.21527529e-11, 3.40033158e-11, 7.02387853e-11,

## Method emitters()
Analysis only using events.

In [22]:
system.emitters(photon_collection_rate=0.9, resample="5ms", emccd_gain=10)

In [23]:
system.emissions

array([ 29,  32,  87, 103, 106, 117, 129, 139, 142, 201, 205, 230, 268,
       284, 287, 297, 317, 319, 351, 360, 371, 383, 400, 403, 441, 445,
       456, 460, 475, 498], dtype=int64)

In [24]:
system.events

array([ 29,  32,  87, 106, 117, 129, 139, 142, 201, 205, 230, 268, 284,
       287, 297, 317, 319, 351, 360, 371, 400, 403, 445, 456, 460, 475,
       498], dtype=int64)

In [25]:
system.time_points_events

array([9.13508611e-08, 1.71748982e-07, 2.42149692e-07, 3.08784952e-07,
       5.27870238e-07, 5.72886721e-07, 5.81610113e-07, 6.38938393e-07,
       7.93994674e-07, 9.29770405e-07, 1.16560518e-06, 1.26709028e-06,
       1.50196748e-06, 1.65473528e-06, 1.85376170e-06, 2.09254448e-06,
       2.10528686e-06, 2.31817933e-06, 2.44040515e-06, 2.48899698e-06,
       2.54081997e-06, 2.54480111e-06, 2.78683882e-06, 2.92753504e-06,
       3.03678610e-06, 3.44784284e-06, 3.54104116e-06])

In [26]:
system.event_time_series

0.00e+00   2.43e+02
dtype: float64

In [27]:
system.on_periods

array([1])

In [28]:
system.off_periods

array([], dtype=int32)

In [29]:
system.emission_statistics

{'total_emissions': 30,
 'total_events': 27,
 'mean_time_between_events': 1.326803961285903e-07}

## Method fcs()

In [30]:
system.fcs(normalize=True, log=True, m=2, deltat=None)

Logarithmic autocorrelation not possible. Event_time_series too short.

C:\Users\SagixOffice\miniconda3\envs\MarkovModels\lib\site-packages\multipletau\core.py:215: RuntimeWarning: divide by zero encountered in double_scalars
  if np.abs(traceavg) / np.median(np.abs(trace)) < ZERO_CUTOFF:

## Parameters

In [31]:
system.parameter_collection

                                                                                    0
init     number_fluorophores                                                        2
         distances                                                                  1
         single_states                                                   [S0, S1, T1]
         transitions                [[S0_S1, 7000000.0, excitation, EXC, False], [...
simulate n_steps                                                                  500
         seed                                                                     100
process  seed                                                                     100
emitters photon_collection_rate                                              9.00e-01
         resample                                                                 5ms
         emccd_gain                                                                10
         threshold                                                                  0
         memory                                                                     0
         remove_heading_off_period                                              False
         seed                                                                     100
fcs      normalize                                                               True
         log                                                                     True
         m                                                                          2
         deltat                                                                   5ms

## Time complexity

In [32]:
mi.time_complexity(mode='number_fluorophores', number_fluorophores=4, simulation_steps_exp=7, seed=100, transitions=transitions)

[68.8288140296936, 69.26811528205872, 70.83010816574097, 73.81850671768188]

Suppose there is an absorbing photophysical state 'B'. The simulation works with joined states, i.e., the absorbing state with 2 fluorophores would be B_B, with three fluorophores B_B_B and so on. The number of simulation steps needed to reach this state scales linearily, meaning that a system of 4 fluorophores needs on average 2 times as many steps as a system of 2 fluorophores to reach this state. \
The time complexity measurement shows that for a fixed amount of simulation steps, the number of fluorophores $n$ does not influence the time. Hence, if the goal is to reach the absorbing state of a system, the time complexity is $\mathcal{O}(n)$.

In [3]:
mi.time_complexity(mode='simulation_steps', number_fluorophores=2, simulation_steps_exp=8, seed=10, transitions=transitions)

[0.050017356872558594,
 0.10936856269836426,
 0.7730987071990967,
 7.71937370300293,
 77.35079503059387,
 932.5235500335693]

Suppose $n$ is the number of simulation steps, then the time complexity is $\mathcal{O}(n)$. For high n, the time complexity might slightly increase due to memory shortage.

## Subclasses

### Cy5

In [6]:
system = fs.Cy5(number_fluorophores=2, distances=1, user=user, irradiance=2.5, wavelength=640, dstorm_parameters=dict())

In [7]:
system.unique_transitions

            name     rate             trivial_name abbreviation  fluorescence
id
0          S0_S1 7.27e+06               excitation          EXC         False
1          S1_S0 2.70e+08     fluorescent emission          FLU          True
2          S1_T1 8.30e+05  intersystem crossing ST        ISCST         False
3          S1_S0 7.09e+08    internal conversion S          ICS         False
4         S1_Cis 2.00e+07            isomerization          ISO         False
5         Cis_S0 1.37e+05        backisomerization         BISO         False
6          T1_S0 5.00e+05  intersystem crossing TS        ISCTS         False
7         T1_OFF 9.60e+06                reduction          RED         False
8         OFF_S0 1.00e+01                oxidation           OX         False
9   S1_S0__S0_S1 1.86e+24    energy transfer HFRET        HFRET         False